added multiple host network aliases for the same interface
hashicorp/nomad pull request #10104
Opened 2021-03-01 10:38 UTC by AndrewChubatiuk

2021-03-24 19:19 UTC, tgross requested changes

2021-03-24 19:19 UTC, tgross commented on nomad/structs/structs.go
> +	Aliases       []string
Unfortunately this approach breaks backwards compatibility for nodes that are already saved in raft. Given that we can already store multiple `NodeNetworkAddress` for a node, we can solve this problem by writing one for each alias from the node fingerprint.

2021-03-24 21:32 UTC, AndrewChubatiuk commented
@tgross I've updated it

2021-04-13 13:08 UTC, tgross commented
LGTM. I've pushed a small style change to the test; you copied what was nearby which was totally the right thing for you to do but we've been using `require` in new tests over the last year or two and have been happy with it.

2021-04-13 13:08 UTC, tgross approved these changes

2021-04-13 13:13 UTC, AndrewChubatiuk commented
@tgross 
okay, thank you

2021-04-13 13:33 UTC, merged