UI: Showed host reservations and allocation utilization by task on existing stats charts
hashicorp/nomad pull request #10208
Opened 2021-03-22 15:58 UTC by DingoEatingFuzz

This applies the new chart patterns to add more information to the existing memory and CPU utilization charts on the client detail, allocation detail, and task detail pages.

## Client Detail

The client detail charts will now show a horizontal annotation (or "high water mark") denoting the [reserved capacity](https://www.nomadproject.io/docs/configuration/client#reserved-resources) for the metric if one has been set.

![client detail stats charts with reserved capacity annotations](https://user-images.githubusercontent.com/174740/112018731-12f6a100-8aec-11eb-98df-f774ebefc120.png)

## Allocation Detail

The allocation detail charts will now break down utilization by task for allocations with multiple tasks.

![allocation detail charts with each task utilization stacked on one canvas](https://user-images.githubusercontent.com/174740/112019178-6a950c80-8aec-11eb-8bbf-a263a861f51a.png)

## Task Detail

The task detail is unchanged. It shows the same data as the allocation detail charts but narrowed down to the single task.

![task detail charts focused on a single task in the same allocation](https://user-images.githubusercontent.com/174740/112019223-754fa180-8aec-11eb-91dc-06e3045f76bb.png)

## Implementation

Since each instance of the previous `PrimaryMetric` component has now deviated, it made sense to refactor it into three components, one for each variation. This resulted in some repetition, but that seemed better than adding even more conditionals and overloading the existing implementation.

There are also some details that arose from using the `StatsTrackers` with Glimmer components.

2021-03-23 17:27 UTC, backspace requested changes
agreed re the desirability of having an overly-general shared component, breaking it up for the variations makes sense to me.

I found a significant problem in that tooltips are broken for me on the allocation chart, but apart from a few tiny notes, this looks good 😀

2021-03-23 17:27 UTC, backspace commented on ui/app/components/primary-metric/node.js
> +    metric null; (one of 'cpu' or 'memory'
tiny: missing `)` (repeated elsewhere)

2021-03-24 21:10 UTC, DingoEatingFuzz commented on ui/app/components/primary-metric/allocation.hbs
> +        </c.Tooltip>
Hmm. Looks like this happens for allocs with lifecycle tasks that haven't started yet. Is that when you encountered it too?

2021-03-24 22:13 UTC, DingoEatingFuzz commented
Okay! I fixed the tooltip bug you caught and another bug with sorting tasks by their lifecycle phase.

2021-03-25 14:18 UTC, backspace approved these changes
nice, indeed fixed for me 🥳

2021-03-25 16:18 UTC, merged