Emit metrics on reschedule later decisions as nomad.client.allocs.reschedule
hashicorp/nomad pull request #10237
Opened 2021-03-25 22:00 UTC by joel0

We implemented this as a companion to #10236 for metrics visibility into rescheduler decisions and limits.

I do not know whether this meets the quality standard to be upstreamed.  If you have ideas on how to make this upstream worthy, I'd be willing to make changes.  I was unable to find a metrics loop that was more appropriate than this with the access to the required alloc info.

2021-03-26 12:45 UTC, tgross commented
Thanks @joel0! We'll take a look -- this is definitely the _sort_ of thing we've been wanting to do to improve scheduler observability.

2022-01-06 03:38 UTC, benbuzbee commented
@tgross just wondering if you folks have had a chance to think about these more. We find them very useful and would be happy to polish the impl to your specifications if it helps

2022-01-06 14:26 UTC, tgross requested changes
Sorry for the delay @benbuzbee @joel0; we've been poking around the scheduler a bunch lately and particular around terminology so I wanted to make sure we're not emitting metrics that are misleading to operators.

I've left a comment about the metric name. But otherwise the implementation for this LGTM. We'll want to add a line to the [metrics reference](https://www.nomadproject.io/docs/operations/metrics-reference) docs and a changelog entry, but I can follow up with those if y'all would like.

2022-01-06 14:26 UTC, tgross commented on scheduler/reconcile.go
> +	baseMetric := []string{"client", "allocs", "reschedule"}
This name would make these fall under [Client Allocation Metrics](https://www.nomadproject.io/docs/operations/metrics-reference#allocation-metrics) that we emit on the clients only. We have few metrics in the scheduler outside the RPC handlers (something we want to fix), so I don't have a good example of a scheduler-internal one. Maybe `[]string{"scheduler", "allocs", "rescheduled"}`?

2022-01-06 20:56 UTC, tgross commented
Actually, I'm going to go ahead and merge this as-is and do the changelog and docs myself... there's a gap in the definitions on that page I want to fill in.

2022-01-06 20:56 UTC, tgross approved these changes
Actually, I'm going to go ahead and merge this as-is and do the changelog and docs myself... there's a gap in the definitions on that page I want to fill in.

LGTM

2022-01-06 20:56 UTC, merged

2022-01-06 21:13 UTC, tgross commented on scheduler/reconcile.go
> +	baseMetric := []string{"client", "allocs", "reschedule"}
fixed the name in https://github.com/hashicorp/nomad/pull/11790