Demo for using CSI on Hetzner Cloud
hashicorp/nomad pull request #10323
Opened 2021-04-07 18:27 UTC by pugnacity

Simple Demo how to use CSI Plugin on Hetzner Cloud

2021-04-07 18:27 UTC, hashicorp-cla commented
[![CLA assistant check](https://cla.hashicorp.com/pull/badge/not_signed)](https://cla.hashicorp.com/hashicorp/nomad?pullRequest=10323)


Thank you for your submission! We require that all contributors sign our Contributor License Agreement ("CLA") before we can accept the contribution. [Read and sign the agreement](https://cla.hashicorp.com/hashicorp/nomad?pullRequest=10323)

[Learn more about why HashiCorp requires a CLA and what the CLA includes](https://www.hashicorp.com/cla)


---
**Sven Winkelmann** seems not to be a GitHub user.
You need a GitHub account to be able to sign the CLA. If you already have a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).

<sub>Have you signed the CLA already but the status is still pending? [Recheck it](https://cla.hashicorp.com/check/hashicorp/nomad?pullRequest=10323).</sub>

2021-04-20 13:28 UTC, mwild1 commented on demo/csi/hetzner/README.md
> +asssumes you already have a Nomad cluster running with the Docker task
Typo: asssumes -> assumes

2021-04-20 13:49 UTC, tgross requested changes
Hi @pugnacity! We've recently merged support for `nomad volume create` but I don't think it's made it out to the Terraform provider yet (and won't be released until the upcoming Nomad 1.1.0). If the Hetnzer plugin supports `CREATE_DELETE_VOLUME` I think we'd rather have that as the workflow shown for the demo. Would you be willing to give that a go?

2021-04-20 13:49 UTC, tgross commented on demo/csi/hetzner/volume-job.nomad
> +        port_map {
This is using deprecated `port_map` syntax. Let's update this to a current version of Nomad's setup for networking.

2021-04-20 13:49 UTC, tgross commented on demo/csi/hetzner/volume-job.nomad
> +}
Let's run hclfmt on these files.

2021-04-22 06:17 UTC, pugnacity commented
> Hi @pugnacity! We've recently merged support for `nomad volume create` but I don't think it's made it out to the Terraform provider yet (and won't be released until the upcoming Nomad 1.1.0). If the Hetnzer plugin supports `CREATE_DELETE_VOLUME` I think we'd rather have that as the workflow shown for the demo. Would you be willing to give that a go?

To be honest, this is my first try with the CSI plugin and I don't feel very confident to build this.
Maybe at a later stage

2023-01-16 17:17 UTC, cberescu commented
Driver version has become outdated and so did the exmaple, the new 2.x branch has different working mechanism 

More info : https://github.com/hetznercloud/csi-driver/issues/330

2023-07-28 20:16 UTC, tgross commented
Given the comment above about the deprecated plugin, I think I'm going to close this out unmerged. I'd also like to note that the Pack Community Registry at https://github.com/hashicorp/nomad-pack-community-registry is a great place for this kind of thing if anyone else wants to pick this up.

2023-07-28 20:16 UTC, closed without merging