e2e: add e2e tests for consul namespaces on ent with acls
hashicorp/nomad pull request #10439
Opened 2021-04-23 18:20 UTC by shoenig

(hold until ent half goes in - making sure oss CI still works)

This PR cherry-picks changes made for ENT testing of Consul Namespaces with ACLs enabled.

2021-04-27 20:22 UTC, tgross requested changes
Looks like there's a stray ENT test file here.

2021-04-27 20:22 UTC, tgross commented on e2e/consul/namespaces_acls_ent.go
> +// +build ent
Should this file be here?

2021-04-27 20:46 UTC, shoenig commented on e2e/consul/namespaces_acls_ent.go
> +// +build ent
Yikes, nope! It's gone now >_>

2021-04-28 12:14 UTC, tgross approved these changes

2021-04-28 12:14 UTC, tgross commented on e2e/consul/namespaces_acls_ent.go
> +// +build ent
Cool. LGTM!

2021-04-28 14:30 UTC, merged