Rookout driver docs
hashicorp/nomad pull request #10950
Opened 2021-07-27 14:34 UTC by lirook

I have added documentation for the Rookout driver.
The driver can be found at https://github.com/Rookout/rookout-nomad-driver

2021-07-27 14:34 UTC, hashicorp-cla commented
[![CLA assistant check](https://cla.hashicorp.com/pull/badge/not_signed)](https://cla.hashicorp.com/hashicorp/nomad?pullRequest=10950)


Thank you for your submission! We require that all contributors sign our Contributor License Agreement ("CLA") before we can accept the contribution. [Read and sign the agreement](https://cla.hashicorp.com/hashicorp/nomad?pullRequest=10950)

[Learn more about why HashiCorp requires a CLA and what the CLA includes](https://www.hashicorp.com/cla)

<sub>Have you signed the CLA already but the status is still pending? [Recheck it](https://cla.hashicorp.com/check/hashicorp/nomad?pullRequest=10950).</sub>

2021-07-28 10:42 UTC, jrasell requested changes
Hi @lirook and thanks very much for this PR and the driver work. Would you be able to update the [index](https://github.com/hashicorp/nomad/blob/main/website/content/docs/drivers/external/index.mdx) page to include a link to this new page?

2021-07-28 10:42 UTC, jrasell commented on website/content/docs/drivers/external/rookout.mdx
> +The `java-rookout` driver accepts all configuration options of the `java` driver.
Could we link out to the Java driver configuration options here?

2021-07-29 11:40 UTC, jrasell requested changes
Thanks for the addition commits @lirook. I have one final change suggestion which alters the ordering of the description and removes the word "disruptive". This is a follow up due to some async internal discussion.

I will also push a commit before merging to move the ordering on the index page to alphabetical; so there is no bias or ambiguity on where additions should be placed.

2021-07-29 11:40 UTC, jrasell commented on website/content/docs/drivers/external/rookout.mdx
> +More info about the Rookout SDK is available in the [Rookout docs](https://docs.rookout.com).
```suggestion
The Rookout Nomad driver is used to execute Java applications packaged into a Java Jar file and automatically add the Rookout SDK to them.

[Rookout](https://rookout.com) is a developer solution for Cloud Native debugging and live-data collection. Rookout’s Non-Breaking Breakpoints let you collect any type of data on the fly with no extra coding, redeployments, or restarts.

More info about the Rookout SDK is available in the [Rookout docs](https://docs.rookout.com).
```

2021-07-29 11:59 UTC, lirook commented
Thank you @jrasell !
I committed the suggested changes.
Let me know if there's anything else you need me to update.

2021-08-02 08:06 UTC, jrasell approved these changes
LGTM thanks @lirook!

2021-08-02 08:09 UTC, merged