fingerprint: check if the CNI bridge plugin is available
hashicorp/nomad pull request #11038
Opened 2021-08-11 18:11 UTC by notnoop

A client should declare the "bridge" network fingerprint only if the
bridge CNI plugin is available.

Currently, Linux clients with the bridge kernel module enabled (pretty
much all Linux boxes with Docker installed) declare "bridge" network,
but allocs requiring it will fail with `failed to find plugin "bridge"
in path [/opt/cni/bin]` error.

Related to https://github.com/hashicorp/nomad/pull/11034

2021-08-13 20:11 UTC, schmichael commented on client/fingerprint/bridge_linux.go
> +		f.logger.Warn("failed to dtect bridge network setup, bridge network mode disabled", "error", err)
```suggestion
		f.logger.Warn("failed to detect bridge network setup, bridge network mode disabled", "error", err)
```

2021-08-13 20:17 UTC, schmichael requested changes

2021-08-13 20:17 UTC, schmichael commented on client/fingerprint/bridge_linux.go
> +		return fmt.Errorf("cni is not configured")
```suggestion
		return fmt.Errorf("cni_path is not configured")
```

2021-08-13 20:17 UTC, schmichael commented on client/fingerprint/bridge_linux.go
> +	}
`cni_path` can contain multiple `:` delimited paths, so this needs to use `filepath.SplitList` and loop over the paths.

- docs - https://www.nomadproject.io/docs/configuration/client#cni_path
- code - https://github.com/hashicorp/nomad/blob/v1.1.3/client/allocrunner/networking_cni.go#L75-L76

2021-11-10 21:43 UTC, hashicorp-cla commented
[![CLA assistant check](https://cla.hashicorp.com/pull/badge/not_signed)](https://cla.hashicorp.com/hashicorp/nomad?pullRequest=11038)


Thank you for your submission! We require that all contributors sign our Contributor License Agreement ("CLA") before we can accept the contribution. [Read and sign the agreement](https://cla.hashicorp.com/hashicorp/nomad?pullRequest=11038)

[Learn more about why HashiCorp requires a CLA and what the CLA includes](https://www.hashicorp.com/cla)


---
**Mahmood Ali** seems not to be a GitHub user.
You need a GitHub account to be able to sign the CLA. If you already have a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).

<sub>Have you signed the CLA already but the status is still pending? [Recheck it](https://cla.hashicorp.com/check/hashicorp/nomad?pullRequest=11038).</sub>

2023-04-19 02:23 UTC, lgfa29 commented
Closing this one as it was implemented in https://github.com/hashicorp/nomad/pull/15452.

2023-04-19 02:23 UTC, closed without merging