scheduler: warn when system jobs cannot place an alloc
hashicorp/nomad pull request #11111
Opened 2021-08-31 21:01 UTC by notnoop

When a system or sysbatch job specify constraints that none of the current nodes meet, report a warning to the user.

Also, for sysbatch job, mark the job as dead if no allocation is placed at all. System jobs behavior isn't affected by this.

A sample run would look like:

```
$ nomad job run ./example.nomad
==> 2021-08-31T16:57:35-04:00: Monitoring evaluation "b48e8882"
    2021-08-31T16:57:35-04:00: Evaluation triggered by job "example"
==> 2021-08-31T16:57:36-04:00: Monitoring evaluation "b48e8882"
    2021-08-31T16:57:36-04:00: Evaluation status changed: "pending" -> "complete"
==> 2021-08-31T16:57:36-04:00: Evaluation "b48e8882" finished with status "complete" but failed to place all allocations:
    2021-08-31T16:57:36-04:00: Task Group "cache" (failed to place 1 allocation):
      * Constraint "${meta.tag} = bar": 2 nodes excluded by filter
      * Constraint "${attr.kernel.name} = linux": 1 nodes excluded by filter

$ nomad job status example
ID            = example
Name          = example
Submit Date   = 2021-08-31T16:57:35-04:00
Type          = sysbatch
Priority      = 50
Datacenters   = dc1
Namespace     = default
Status        = dead
Periodic      = false
Parameterized = false

Summary
Task Group  Queued  Starting  Running  Failed  Complete  Lost
cache       0       0         0        0       0         0

Allocations
No allocations placed
```

2021-09-02 13:01 UTC, notnoop commented on scheduler/scheduler_sysbatch_test.go
> +	require.NoError(t, nodeBTwo.ComputeClass())
Good catch!

2021-09-02 13:01 UTC, notnoop commented on scheduler/scheduler_sysbatch_test.go
> +	require.Equal(t, 1, len(h.Evals[2].FailedTGAllocs))
[`require.Len`](https://pkg.go.dev/github.com/stretchr/testify/require#Len) is a handy test for this; on failure, it prints the map so we can inspect state of map to understand how the count differed.

```suggestion
	require.Len(t, h.Evals[2].FailedTGAllocs, 1)
```

2021-09-02 16:10 UTC, lgfa29 approved these changes

2021-09-02 16:16 UTC, lgfa29 commented
@notnoop I pushed a changelog entry, but I'm not sure if it's good. Feel free to change it before merge.

2021-09-02 23:13 UTC, schmichael requested changes
@notnoop is out, so I'll try to move this forward! I'm not sure my comment is a blocker, but I'd like to check it out before merging.

2021-09-02 23:13 UTC, schmichael commented on scheduler/scheduler_system.go
> +		return &v
Shallow copying means referenced values in `curr` on the first call will be mutated on successive calls.

2021-09-02 23:14 UTC, schmichael commented on .changelog/11111.txt
> +scheduler: Keep track of system and sysbatch evaluations that fail to place an allocation
```suggestion
scheduler: Warn users when system and sysbatch evaluations that fail to place an allocation
```

While I don't think this fully encompasses the changes, other bits like marking sysbatch as `dead` immediately are new so haven't changed from a previous release.

2021-09-13 23:05 UTC, schmichael approved these changes

2021-09-13 23:06 UTC, merged