Update metrics.mdx
hashicorp/nomad pull request #11468
Opened 2021-11-07 07:39 UTC by kfenech1

I believe the nomad.client.unallocated.memory is in Megabytes and not bytes.

2021-11-07 07:39 UTC, hashicorp-cla commented
[![CLA assistant check](https://cla.hashicorp.com/pull/badge/not_signed)](https://cla.hashicorp.com/hashicorp/nomad?pullRequest=11468)


Thank you for your submission! We require that all contributors sign our Contributor License Agreement ("CLA") before we can accept the contribution. [Read and sign the agreement](https://cla.hashicorp.com/hashicorp/nomad?pullRequest=11468)

[Learn more about why HashiCorp requires a CLA and what the CLA includes](https://www.hashicorp.com/cla)

<sub>Have you signed the CLA already but the status is still pending? [Recheck it](https://cla.hashicorp.com/check/hashicorp/nomad?pullRequest=11468).</sub>

2021-11-08 14:24 UTC, tgross requested changes
Thanks @kfenech1! I checked the code in [`client/client.go#L2926`](https://github.com/hashicorp/nomad/blob/94b127e897406ab1810a13076b18765dc74ca70b/client/client.go#L2926) and that looks right to me!

I left a minor correction on the metric name, but once that is fixed and CLA is signed we can merge this in. Thanks again!

2021-11-08 14:24 UTC, tgross commented on website/content/docs/operations/metrics.mdx
> +| `nomad.client.unallocated_memory`       | Total amount of memory free for the scheduler to allocate to tasks                  | Megabytes  | Gauge | datacenter, host, node_class, node_id, node_sche
I had to look up the metric in the code to verify this PR, and it turns out there should be a `.` and not `_` in the name:

```suggestion
| `nomad.client.unallocated.memory`       | Total amount of memory free for the scheduler to allocate to tasks                  | Megabytes  | Gauge | datacenter, host, node_class, node_id, node_scheduling_eligibility, node_status       |
```

2021-11-08 15:51 UTC, kfenech1 commented
Hi @tgross,

That is correct it should be a . instead of an _ . I added your suggestion and signed the CLA. 

Thanks

2021-11-08 16:04 UTC, tgross approved these changes
LGTM

2021-11-08 16:05 UTC, merged