Add filters to Allocations
hashicorp/nomad pull request #11544
Opened 2021-11-20 15:51 UTC by ChaiWithJai

Mock
![image](https://user-images.githubusercontent.com/41024828/142732663-a2d65f1e-1b7a-4031-afd0-d9611a4ee6fb.png)

Actual
![image](https://user-images.githubusercontent.com/41024828/142732659-0090e7e7-e71a-496d-b68f-94045d092cf2.png)

2021-11-23 19:11 UTC, lgfa29 requested changes
Looking good! 

Filtering by status doesn't work because the filter is reading the wrong alloc property (`status` vs `clientStatus`). It would be good to have some tests for this as well, they would've likely caught this problem. Take a look at other pages with filters to see how they are done.

I think filtering by job version would could be helpful as well, and seems like a quick addition. But feel free to drop it if it's not.

2021-11-23 19:11 UTC, lgfa29 commented on ui/app/controllers/jobs/job/allocations.js
> +      if (selectionStatus.length && !selectionStatus.includes(alloc.status)) {
```suggestion
      if (selectionStatus.length && !selectionStatus.includes(alloc.clientStatus)) {
```

2021-11-23 19:11 UTC, lgfa29 commented on ui/app/controllers/jobs/job/allocations.js
> +    return clients.sort().map(dc => ({ key: dc, label: dc }));
```suggestion
    return clients.sort().map(c => ({ key: c, label: c }));
```

2021-11-23 19:11 UTC, lgfa29 commented on ui/app/controllers/jobs/job/allocations.js
> +    return taskGroups.sort().map(dc => ({ key: dc, label: dc }));
```suggestion
    return taskGroups.sort().map(tg => ({ key: tg, label: tg }));
```

2021-11-23 22:53 UTC, ChaiWithJai commented on ui/app/controllers/jobs/job/allocations.js
> +  /*eslint-disable  indent */
I can't fix it.

2021-12-17 14:15 UTC, LevelbossMike commented on ui/app/controllers/jobs/job/allocations.js
> +    const clients = Array.from(new Set(this.model.allocations.mapBy('node.shortId'))).compact();
We are repeating this multiple times in this file. I understand that this pattern is used in other places as well `controllers/clients/index.js` for example. It looks like we can create a computed-macro out of this pattern.

2021-12-17 14:15 UTC, LevelbossMike commented on ui/app/controllers/jobs/job/allocations.js
> +      this.set('qpClient', serialize(intersection(clients, this.selectionClient)));
we probably don't want to trigger side-effects in computeds. Again this is done in other places as well but we should investigate why we feel this is necessary to do

2021-12-17 14:15 UTC, LevelbossMike commented on ui/app/controllers/jobs/job/allocations.js
> +    if (!allocations.length) return allocations;
we can just work with `model.allocation` directly here probably - i.e. directly go to the filter.

2021-12-17 14:40 UTC, LevelbossMike approved these changes
We can tackle the macro in a follow-up PR and apply it to the rest of the codebase that also uses this pattern.

Good work! 👏

2021-12-18 01:05 UTC, lgfa29 approved these changes
> I think filtering by job version would could be helpful as well

On second thought, it wasn't very helpful. Long-lived jobs can have their version in the hundreds (if not thousands), the filter list would be pretty useless and hard to use. 

So I removed this filter. Sorry for the unnecessary work 😅

2021-12-18 14:38 UTC, merged