qemu driver: Add option to configure drive_interface
hashicorp/nomad pull request #11864
Opened 2022-01-15 22:01 UTC by bogue1979

For QEMU the options `-drive file=image.img` and `-drive file=image.img,if=ide` are identical. 
This change will use the second variant as default and allow to define an image file using the virtio driver inside of the VM.
Using this driver should improve the disk IO a lot.

2022-03-11 13:19 UTC, bogue1979 commented
Ping

2022-03-12 16:58 UTC, hashicorp-cla commented
[![CLA assistant check](https://cla.hashicorp.com/pull/badge/not_signed)](https://cla.hashicorp.com/hashicorp/nomad?pullRequest=11864)


Thank you for your submission! We require that all contributors sign our Contributor License Agreement ("CLA") before we can accept the contribution. [Read and sign the agreement](https://cla.hashicorp.com/hashicorp/nomad?pullRequest=11864)

[Learn more about why HashiCorp requires a CLA and what the CLA includes](https://www.hashicorp.com/cla)

<sub>Have you signed the CLA already but the status is still pending? [Recheck it](https://cla.hashicorp.com/check/hashicorp/nomad?pullRequest=11864).</sub>

2022-03-31 14:53 UTC, tgross reviewed
Hi @bogue1979! This looks great. I think the only thing that comes to mind here is being sure about the default behavior for QEMU. Do you know if `ide` is platform-specific behavior and that QEMU isn't doing something "smart" based on the available interfaces on the platform? I want to make sure we're not introducing a breaking change, and that we're not boxing ourselves in for future updates we have on the roadmap for expanding QEMU support beyond x86_64 platform.

The [man page](https://linux.die.net/man/1/qemu-kvm) has this to say:
> if=interface
> This option defines on which type on interface the drive is connected. Available types are: ide, scsi, sd, mtd, floppy, pflash, virtio.

With nothing about the default.

2022-04-13 20:59 UTC, bogue1979 commented
> Hi @bogue1979! This looks great. I think the only thing that comes to mind here is being sure about the default behavior for QEMU. Do you know if `ide` is platform-specific behavior and that QEMU isn't doing something "smart" based on the available interfaces on the platform? I want to make sure we're not introducing a breaking change, and that we're not boxing ourselves in for future updates we have on the roadmap for expanding QEMU support beyond x86_64 platform.
> 
> The [man page](https://linux.die.net/man/1/qemu-kvm) has this to say:
> 
> > if=interface
> > This option defines on which type on interface the drive is connected. Available types are: ide, scsi, sd, mtd, floppy, pflash, virtio.
> 
> With nothing about the default.

Honestly I have no possibility to test another architecture. When I run a VM only with `file=image.img` on linux_x64, qemu implicitly attaches a virtual `ide` disk. On the other side giving the option to explicitly configure the interface, any non default behaviour can be overriden within the nomad job file. I guess if another architecture does not understand the given `ide` interface updating the documentation should be sufficient.

2022-06-01 16:56 UTC, bogue1979 commented
@tgross 
any news on this?

2022-06-09 13:46 UTC, tgross requested changes
Sorry about the delayed follow-up @bogue1979. This looks pretty good.

You haven't made the PR editable by maintainers, so I'll also need you to add a changelog entry at `.changelog/11864.txt` with the following contents:

    ```release-note:improvement
    qemu: Added option to configure `drive_interface`
    ```

Once that's done we can get this merged and shipped in the upcoming Nomad 1.3.2

2022-06-09 13:46 UTC, tgross commented on drivers/qemu/driver.go
> +	for _, ai := range interfaceList {
This isn't in a hot path, but no reason to allocate this whole list for each function call:

```suggestion
// hardcoded list of drive interfaces, Qemu currently supports
var allowedDriveInterfaces = []string{"ide", "scsi", "sd", "mtd", "floppy", "pflash", "virtio", "none"}

func isAllowedDriveInterface(driveInterface string) bool {
	for _, ai := range allowedDriveInterfaces {
```

2022-06-10 13:44 UTC, tgross approved these changes
LGTM! Thanks for your patience on this one @bogue1979 !

2022-06-10 13:50 UTC, bogue1979 commented
Sorry I'm not really a developer and Git sometimes confuses me when it does not work as expected.

2022-06-10 14:03 UTC, tgross approved these changes

2022-06-10 14:03 UTC, merged