fix(alloc/exec): trim spaces on secretID to prevent error on lookup
hashicorp/nomad pull request #11897
Opened 2022-01-21 12:05 UTC by Thunderbottom

If the ACL Token set in localstorage contains prefixed/suffixed spaces, any RPC calls to `Allocations.Exec` results in:

```
  Connection Closed: 1011 acl token lookup failed: index error: UUID must be 36 characters
```

### How to reproduce:

1. Set token in `https://<nomad-instance>/ui/settings/tokens`, preferably with an added space before the token. The token gets set correctly, which means that the system is handling spaces just fine.

2. Exec into any allocation through the web UI, which would fail as described above.

### Sample Request Payload:

```json
{
  "version": 1,
  "auth_token": " XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX",
}
```

Notice the prefixed added space in the `auth_token` value which causes the error.

### Proposed fix:

RPC to `Allocations.Exec` calls `ACLTokenBySecretID()`, which should pass the space-trimmed `secretID` to lookup the ACL token. A simple `strings.TrimSpace()` call around `secretID` should fix the issue.

2022-01-24 15:19 UTC, tgross requested changes
Hi @Thunderbottom! Thanks for opening this PR!

I think it's arguable whether or not we should be doing this in the API but this should definitely not be touched at the state store level. We should be doing any input validation "further out". Can you rework this so that it's happening when we initially validate the request?

2022-01-25 07:22 UTC, Thunderbottom commented
> I think it's arguable whether or not we should be doing this in the API but this should definitely not be touched at the state store level.

Hm, I believe prefixed and suffixed spaces have very little to contribute anyways to the token and can be stripped at store level validations. Could you let me know of any specific concerns that would make you vary of making such changes at this level?

> Can you rework this so that it's happening when we initially validate the request?

Do you mean at the UI front or the backend? The current implementation handles all validation cases regardless where there's spaces in the token. I'd be more than happy to rework this if you point me to where I should be making changes. Sorry if that's asking for too much from you, and thanks for your time :)

2022-01-25 15:59 UTC, tgross commented
> Could you let me know of any specific concerns that would make you vary of making such changes at this level?

Primarily separation of concerns and long-term maintainability. Keeping validation code together makes sure we don't have parts of the code base that are handling unvalidated code when they shouldn't be.

> Do you mean at the UI front or the backend? The current implementation handles all validation cases regardless where there's spaces in the token. I'd be more than happy to rework this if you point me to where I should be making changes. Sorry if that's asking for too much from you, and thanks for your time :)

Where we parse the token from the header in the HTTP server seems like the right place for this kind of thing, I think? See [`http.go#L744-L750`](https://github.com/hashicorp/nomad/blob/main/command/agent/http.go#L744-L750). That way _every_ endpoint enjoys the fix and not just alloc/exec, right?

2022-03-12 16:57 UTC, hashicorp-cla commented
[![CLA assistant check](https://cla.hashicorp.com/pull/badge/not_signed)](https://cla.hashicorp.com/hashicorp/nomad?pullRequest=11897)


Thank you for your submission! We require that all contributors sign our Contributor License Agreement ("CLA") before we can accept the contribution. [Read and sign the agreement](https://cla.hashicorp.com/hashicorp/nomad?pullRequest=11897)

[Learn more about why HashiCorp requires a CLA and what the CLA includes](https://www.hashicorp.com/cla)

<sub>Have you signed the CLA already but the status is still pending? [Recheck it](https://cla.hashicorp.com/check/hashicorp/nomad?pullRequest=11897).</sub>

2023-03-13 20:13 UTC, tgross commented
It's been a bit since we've heard back on this, so going to close this in lieu of https://github.com/hashicorp/nomad/pull/16469. But thanks for bringing this to our attention!

2023-03-13 20:13 UTC, closed without merging