client: reconnect unknown allocations
hashicorp/nomad pull request #12086
Opened 2022-02-17 23:13 UTC by DerekStrickland

This PR includes a client change that synchronizes client/server state when unknown allocations reconnect

- The server gets the current `ClientStatus` and `ClientDescription` from the client
- The client gets the current indexes from the server

2022-02-18 14:14 UTC, tgross requested changes

2022-02-22 10:07 UTC, DerekStrickland commented on client/client_test.go
> +			fmt.Sprintf("expected running client status, but got %v", alloc.ClientStatus))
Hands thank you for saving me this typing. Resolved in next push.

2022-02-22 10:17 UTC, DerekStrickland commented on client/client_test.go
> +	require.Equal(t, structs.AllocClientStatusRunning, unknownAlloc.ClientStatus)
Fixed in next push.

2022-02-22 12:06 UTC, DerekStrickland commented on client/client_test.go
> +		require.NotNil(t, ar, "expected alloc runner")
Ready for review

2022-02-22 14:49 UTC, tgross approved these changes
LGTM!

2022-02-22 14:59 UTC, merged