Fix exec -job not finding jobs on wildcard namespace
hashicorp/nomad pull request #12097
Opened 2022-02-20 11:58 UTC by leonardobsjr

Right now, nomad exec -job is inconsistent with other commands like nomad status in the sense that it can't find an existing job if nomad namespace is '*'. The reason for that is that AllocsByJob doesn't handle '*' properly as a nomad namespace value - it tries to search MemDB by using * and finds nothing because the jobs are registered in proper namespaces. To fix this, if the nomad namespace is '*', it searches on all namespaces and fails if the JobID exists on multiple namespaces.

I'm pretty sure I should have written some tests over this, but I would love some guidance on where :)

2022-02-20 11:58 UTC, hashicorp-cla commented
[![CLA assistant check](https://cla.hashicorp.com/pull/badge/not_signed)](https://cla.hashicorp.com/hashicorp/nomad?pullRequest=12097)


Thank you for your submission! We require that all contributors sign our Contributor License Agreement ("CLA") before we can accept the contribution. [Read and sign the agreement](https://cla.hashicorp.com/hashicorp/nomad?pullRequest=12097)

[Learn more about why HashiCorp requires a CLA and what the CLA includes](https://www.hashicorp.com/cla)


---
**Leonardo Jr** seems not to be a GitHub user.
You need a GitHub account to be able to sign the CLA. If you already have a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).

<sub>Have you signed the CLA already but the status is still pending? [Recheck it](https://cla.hashicorp.com/check/hashicorp/nomad?pullRequest=12097).</sub>

2022-02-22 13:45 UTC, tgross requested changes
Hi @leonardobsjr! Thanks for the PR!

The error message you've got around `job %s exist on multiple namespaces` really suggests that this fix isn't being implemented at the right place in the code base. `AllocsByJob` has a _lot_ of callers, particularly in the scheduler, so behavior changes here have a lot of ripple effects.

The command implementation ref [`alloc_exec.go#L163`](https://github.com/hashicorp/nomad/blob/v1.2.6/command/alloc_exec.go#L163) calls a [`getRandomJobAlloc`](https://github.com/hashicorp/nomad/blob/v1.2.6/command/alloc_fs.go#L381) that's expecting a specific job ID but using the command's namespace. If we hit the [ListJobs](https://www.nomadproject.io/api-docs/jobs#list-jobs) API we can get a list of the jobs that match the namespace + ID, and that'll give us an opportunity here to either silently continue (if there's only one job that works) or return a meaningful error message to the user. If we did this in the `getRandomJobAlloc` command we'd enjoy the benefit of your work on `nomad alloc fs` commands too!

2023-07-28 20:13 UTC, tgross commented
Hi @leonardobsjr I was doing a little tidying up on a Friday afternoon and saw this was still open. I've opened https://github.com/hashicorp/nomad/pull/18095 as an alternative implementation.

2023-07-28 20:13 UTC, closed without merging

2023-07-31 11:56 UTC, leonardobsjr commented
Awesome! Sorry for not following up on this. Thanks for the ping @tgross !