wip add json jobspec support to cli
hashicorp/nomad pull request #12591
Opened 2022-04-16 00:17 UTC by schmichael

While the CLI has always supported running JSON jobs, its support has
been via HCLv2's JSON parsing. I have no idea what format it expects the
job to be in, but it's absolutely not in the same format as the API
expects.

So I ignored that and added a new -json flag to explicitly support *API*
style JSON jobspecs.

The jobspecs can even have the wrapping {"Job": {...}} envelope or not!

Lots left to do:

- Changelog
- Docs
- Tests
- plan and validate support
- Can we remove, warn, or deprecate the weird HCL+JSON support?

2022-04-20 12:04 UTC, jrasell approved these changes
Awesome!!!

2022-04-20 12:05 UTC, jrasell requested changes
I missed the test failure on my original review. It looks like the plan command is failing with a redefined flag:
```
panic: job plan flag redefined: hcl1 [recovered]
	panic: job plan flag redefined: hcl1

goroutine 19967 [running]:
testing.tRunner.func1.2({0x22f6e60, 0xc003aae680})
	/usr/local/go/src/testing/testing.go:1209 +0x24e
testing.tRunner.func1()
	/usr/local/go/src/testing/testing.go:1212 +0x218
panic({0x22f6e60, 0xc003aae680})
	/usr/local/go/src/runtime/panic.go:1038 +0x215
flag.(*FlagSet).Var(0xc0042ff920, {0x2ea2d28, 0xc0048eb3b0}, {0x2907e23, 0x4}, {0x0, 0x0})
	/usr/local/go/src/flag/flag.go:879 +0x2f4
flag.(*FlagSet).BoolVar(...)
	/usr/local/go/src/flag/flag.go:632
github.com/hashicorp/nomad/command.(*JobPlanCommand).Run(0xc0048eb300, {0xc004f6f410, 0x3, 0x3})
	/home/circleci/go/src/github.com/hashicorp/nomad/command/job_plan.go:142 +0x237
github.com/hashicorp/nomad/command.TestPlanCommand_Fails(0xc00429b6c0)
	/home/circleci/go/src/github.com/hashicorp/nomad/command/job_plan_test.go:33 +0x198
testing.tRunner(0xc00429b6c0, 0x2a227d8)
	/usr/local/go/src/testing/testing.go:1259 +0x102
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:1306 +0x35a
	``

2022-04-20 23:52 UTC, lgfa29 approved these changes
```console
$ nomad job inspect example | jq '.Job.TaskGroups[0].Count = 2' | nomad job run -json -
```

🎉 

Just needs a quick fix in the CHANGELOG file.

2022-04-20 23:52 UTC, lgfa29 commented on .changelog/12591.txt
> +cli: Added -json flag to `nomad job {run,plan,validate}` to support parsing JSON formatted jobs
Missing the closing backticks

2022-04-21 00:02 UTC, schmichael commented on .changelog/12591.txt
> +cli: Added -json flag to `nomad job {run,plan,validate}` to support parsing JSON formatted jobs
:facepalm:

2022-04-21 09:03 UTC, jrasell approved these changes

2022-04-21 20:20 UTC, merged