warn destructive update only when count > 1
hashicorp/nomad pull request #13103
Opened 2022-05-24 10:42 UTC by yaroot

The warning doesn't make sense when count is 0 or 1 (destructive anyway). It's distractive and may cause users to ignore useful warnings.

2022-05-25 14:35 UTC, yaroot commented
@Amier3 I've opened #13116 for this

2022-06-01 00:06 UTC, lgfa29 requested changes
Thanks for the PR @yaroot!

Would you mind adding some test cases to [`TestJob_Warnings`](https://github.com/hashicorp/nomad/blob/3d45dcb64a7dbb0c67b3bddd7bcf3bdeee9e49c1/nomad/structs/structs_test.go#L175) to check this condition?

And also add a [`CHANGELOG` entry](https://github.com/hashicorp/nomad/blob/main/contributing/CHANGELOG.md) for this change.

2022-09-01 09:10 UTC, yaroot commented
@lgfa29 can you take a look

2022-09-02 19:29 UTC, lgfa29 approved these changes
Looks good, thank you 😄

2022-09-02 19:30 UTC, merged