document lxc task config option
hashicorp/nomad pull request #13349
Opened 2022-06-13 16:39 UTC by h0tw1r3

Document https://github.com/hashicorp/nomad-driver-lxc/pull/38

2022-06-13 16:47 UTC, DerekStrickland requested changes
Thanks for submitting this!  I have a quick request to make the md links consistent. Please see inline. You can just accept the suggestions and it will apply a patch.

2022-06-13 16:52 UTC, h0tw1r3 commented on website/content/plugins/drivers/community/lxc.mdx
> +[lxc.conf]: https://linuxcontainers.org/lxc/manpages/man5/lxc.conf.5.html
done

2022-06-13 16:52 UTC, h0tw1r3 commented on website/content/plugins/drivers/community/lxc.mdx
> +- `config_file` - The `lxc` configuration file to load (commonly defaults to `/etc/lxc/default.conf`). See [`lxc.conf`][lxc.conf] for more details.
done

2022-06-13 19:34 UTC, DerekStrickland approved these changes
Looks good to me.  Tagging @lgfa29  for a second set of eyes.

2022-07-05 20:29 UTC, tgross reviewed
Note this blocked on merging https://github.com/hashicorp/nomad-driver-lxc/pull/38

2024-10-10 15:06 UTC, aimeeu commented
Nomad 1.9 removes the deprecated LXC driver so I'm closing this PR.

2024-10-10 15:06 UTC, closed without merging