fix(#13844): canonicalize job to avoid nil pointer deference
hashicorp/nomad pull request #13845
Opened 2022-07-19 15:23 UTC by tristanpemble

I am new to this codebase, so unsure I have the best approach, but this fixes my issue in #13844. I traced the issue down to the nil pointer [here](https://github.com/hashicorp/nomad/blob/208b68221184fe5712272c13f4f307373fb9117e/api/jobs.go#L792), which is called [from this path](https://github.com/hashicorp/nomad/blob/208b68221184fe5712272c13f4f307373fb9117e/command/job_run.go#L349-L355).

This code is called after the job registration succeeds on the server. I believe the root of the issue is that when submitting an API job via the CLI, it is canonicalized server-side, but not client-side. Registration succeeds on the server, and then this code path is called. It references paths that have not been canonicalized with their default values, and fails.

Another option would be to canonicalize the job before registration (maybe in the `JobGetter` when loading the job?), but being new to the codebase, I am wary of the unintended change in behavior that might create for endusers.

2022-07-19 15:23 UTC, hashicorp-cla commented
[![CLA assistant check](https://cla.hashicorp.com/pull/badge/not_signed)](https://cla.hashicorp.com/hashicorp/nomad?pullRequest=13845)


Thank you for your submission! We require that all contributors sign our Contributor License Agreement ("CLA") before we can accept the contribution. [Read and sign the agreement](https://cla.hashicorp.com/hashicorp/nomad?pullRequest=13845)

[Learn more about why HashiCorp requires a CLA and what the CLA includes](https://www.hashicorp.com/cla)

<sub>Have you signed the CLA already but the status is still pending? [Recheck it](https://cla.hashicorp.com/check/hashicorp/nomad?pullRequest=13845).</sub>

2022-07-20 20:00 UTC, Amier3 commented
Hey @tristanpemble 

Thanks for making this PR and congrats on the first contribution. We'll take a look at this soon 😄

2022-07-25 13:47 UTC, tgross requested changes
Hi @tristanpemble! Thanks for this PR!

The fix you've got here will totally work for the case of the CLI, but it'll still be broken for other consumers of the HTTP API. The panic you've hit in https://github.com/hashicorp/nomad/issues/13844 is at [`api/jobs.go#L788`](https://github.com/hashicorp/nomad/blob/v1.3.1/api/jobs.go#L788). The `p` pointer is nil, and that causes the panic when we try to access one of its fields. But in this case, we have a safe fallback behavior later in the `Next` method. So a fix like the diff below should fix both the CLI panic you've hit and prevent anyone else from hitting the same bug if they don't call `Canonicalize()`:

```diff
-if *p.SpecType == PeriodicSpecCron {
+if p != nil && *p.SpecType == PeriodicSpecCron {
```

If you can make this change I'd be happy to get this PR merged. You can also add a changelog entry file at `.changelog/13845.txt` with the following text:

    ```improvement
    api: Fixed a bug where accessing the next periodic invocation for a job could panic if not set
    ```

2022-07-25 13:47 UTC, tgross commented on command/job_run.go
> +	// #13844: canonicalize the job in case it was a partial API definition
Just FYI, there's no need to have the issue number in the comments. That's what `git blame` is for 😀

2023-02-01 19:56 UTC, tgross commented
Hi! :wave: I want to get this PR landed in the upcoming Nomad 1.5.0, so I've pushed a commit with the requested fix and a changelog entry. Once that's green I'll get this merged.

2023-02-01 20:01 UTC, tgross approved these changes

2023-02-01 21:01 UTC, merged