Add a log line to help track node eligibility
hashicorp/nomad pull request #14125
Opened 2022-08-15 21:50 UTC by Kellel

Often when debugging issues with our nomad cluster we find that it can
be difficult to correlate manual and automated actions against the
cluster state as nodes are brought into and out of production.

This doesn't fix #8965, but it is something to help minimize the inconvenience in the meantime.

2022-08-15 21:50 UTC, hashicorp-cla commented
[![CLA assistant check](https://cla.hashicorp.com/pull/badge/not_signed)](https://cla.hashicorp.com/hashicorp/nomad?pullRequest=14125)


Thank you for your submission! We require that all contributors sign our Contributor License Agreement ("CLA") before we can accept the contribution. [Read and sign the agreement](https://cla.hashicorp.com/hashicorp/nomad?pullRequest=14125)

[Learn more about why HashiCorp requires a CLA and what the CLA includes](https://www.hashicorp.com/cla)


---
**Kellen Fox** seems not to be a GitHub user.
You need a GitHub account to be able to sign the CLA. If you already have a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).

<sub>Have you signed the CLA already but the status is still pending? [Recheck it](https://cla.hashicorp.com/check/hashicorp/nomad?pullRequest=14125).</sub>

2022-08-16 07:33 UTC, jrasell requested changes
Hi @Kellel and thanks for raising this PR which seems very useful to cluster operators. I have suggested some changes for you to look over; the most notable change is to remove the use of `.With` from the logger. This function creates a sublogger with the given kv context always present which we do not need. We can just rely on the message kv formatting for this use case.

2022-08-16 07:33 UTC, jrasell commented on nomad/node_endpoint.go
> +		n.logger.With("node_id", node.ID).Info("Node transitioning to eligible state")
```suggestion
		n.logger.Info("node transitioning to eligible state", "node_id", node.ID)
```

2022-08-16 07:33 UTC, jrasell commented on nomad/node_endpoint.go
> +		n.logger.With("node_id", node.ID).Info("Node transitioning to eligible state")
```suggestion
		n.logger.Info("node transitioning to eligible state", "node_id", node.ID)
```

2022-08-16 07:33 UTC, jrasell commented on nomad/node_endpoint.go
> +		n.logger.With("node_id", node.ID).Info("Node transitioning to ineligible state")
```suggestion
		n.logger.Info("node transitioning to ineligible state", "node_id", node.ID)
```

2022-08-22 16:41 UTC, Kellel commented
Anything else needed here @jrasell ?

2022-09-06 11:55 UTC, jrasell approved these changes
Hi @Kellel thanks for this; I just added a changelog entry and will get this merged.

2022-09-06 12:03 UTC, merged