website: content updates for developer
hashicorp/nomad pull request #14473
Opened 2022-09-06 18:46 UTC by BRKalow

2022-09-06 18:46 UTC, hashicorp-cla commented
[![CLA assistant check](https://cla.hashicorp.com/pull/badge/not_signed)](https://cla.hashicorp.com/hashicorp/nomad?pullRequest=14473)


Thank you for your submission! We require that all contributors sign our Contributor License Agreement ("CLA") before we can accept the contribution. [Read and sign the agreement](https://cla.hashicorp.com/hashicorp/nomad?pullRequest=14473)

[Learn more about why HashiCorp requires a CLA and what the CLA includes](https://www.hashicorp.com/cla)


---
**4** out of **5** committers have signed the CLA.

- [x] ashleemboyer
- [x] tunzor
- [x] BRKalow
- [x] thiskevinwang
- [ ] hashibot-web

<sub>Have you signed the CLA already but the status is still pending? [Recheck it](https://cla.hashicorp.com/check/hashicorp/nomad?pullRequest=14473).</sub>

2022-09-15 14:28 UTC, BRKalow commented on website/Makefile
> +		-e "PREVIEW_MODE=developer"
```suggestion
		-e "PREVIEW_MODE=io"
```

2022-09-15 14:28 UTC, BRKalow commented on website/data/docs-nav-data.json
> +            "href": "/nomad/tutorials/enterprise/production-reference-architecture-vm-with-consul"
```suggestion
            "href": "https://learn.hashicorp.com/tutorials/nomad/production-reference-architecture-vm-with-consul"
```

2022-09-15 14:28 UTC, BRKalow commented on website/data/docs-nav-data.json
> +            "href": "/nomad/tutorials/enterprise/production-deployment-guide-vm-with-consul"
```suggestion
            "href": "https://learn.hashicorp.com/tutorials/nomad/production-deployment-guide-vm-with-consul"
```

2022-09-15 14:28 UTC, BRKalow commented on website/data/docs-nav-data.json
> +        "href": "/nomad/tutorials/manage-clusters"
```suggestion
        "href": "https://learn.hashicorp.com/collections/nomad/manage-clusters"
```

2022-09-15 14:28 UTC, BRKalow commented on website/data/docs-nav-data.json
> +        "href": "/nomad/tutorials/transport-security"
```suggestion
        "href": "https://learn.hashicorp.com/collections/nomad/transport-security"
```

2022-09-15 14:28 UTC, BRKalow commented on website/data/docs-nav-data.json
> +        "href": "/nomad/tutorials/access-control"
```suggestion
        "href": "https://learn.hashicorp.com/collections/nomad/access-control"
```

2022-09-15 14:28 UTC, BRKalow commented on website/data/intro-nav-data.json
> +        "href": "/nomad/tutorials/get-started"
```suggestion
        "href": "https://learn.hashicorp.com/collections/nomad/get-started"
```

2022-09-15 14:28 UTC, BRKalow commented on website/data/intro-nav-data.json
> +        "href": "/nomad/tutorials/get-started/get-started-run"
```suggestion
        "href": "https://learn.hashicorp.com/tutorials/nomad/get-started-run"
```

2022-09-15 14:28 UTC, BRKalow commented on website/data/intro-nav-data.json
> +        "href": "/nomad/tutorials/get-started/get-started-jobs"
```suggestion
        "href": "https://learn.hashicorp.com/tutorials/nomad/get-started-jobs"
```

2022-09-15 14:28 UTC, BRKalow commented on website/data/intro-nav-data.json
> +        "href": "/nomad/tutorials/get-started/get-started-ui"
```suggestion
        "href": "https://learn.hashicorp.com/tutorials/nomad/get-started-ui"
```

2022-09-15 14:28 UTC, BRKalow commented on website/data/intro-nav-data.json
> +        "href": "/nomad/tutorials/get-started/get-started-learn-more"
```suggestion
        "href": "https://learn.hashicorp.com/tutorials/nomad/get-started-learn-more"
```

2022-09-15 14:28 UTC, BRKalow commented on website/scripts/website-build.sh
> +PREVIEW_MODE=developer
```suggestion
PREVIEW_MODE=io
```

2022-09-15 16:33 UTC, BRKalow commented on website/content/docs/upgrade/upgrade-specific.mdx
> +[`Local`]: https://www.consul.io/docs/security/acl/acl-tokens#token-attributes#token-attributes
```suggestion
[`Local`]: https://www.consul.io/docs/security/acl/acl-tokens#token-attributes
```

2022-09-16 14:54 UTC, BRKalow commented on website/content/docs/install/index.mdx
> +\-> If you are interested in trialing Nomad without installing it locally, see the
```suggestion
-> If you are interested in trialing Nomad without installing it locally, see the
```

2022-09-16 14:54 UTC, BRKalow commented on website/content/docs/install/index.mdx
> +\-> **Tip (Linux-based or Mac):** Permanently add a new location to your path by
```suggestion
-> **Tip (Linux-based or Mac):** Permanently add a new location to your path by
```

2022-09-16 14:54 UTC, BRKalow commented on website/content/docs/install/index.mdx
> +\-> **Tip (Windows):** Add a location to your path via the GUI by navigating to
```suggestion
-> **Tip (Windows):** Add a location to your path via the GUI by navigating to
```

2022-09-16 14:54 UTC, BRKalow commented on website/content/docs/install/index.mdx
> +\-> **TIP:** Now that you have added the HashiCorp repository, you can install
```suggestion
-> **TIP:** Now that you have added the HashiCorp repository, you can install
```

2022-09-16 14:54 UTC, BRKalow commented on website/content/docs/install/index.mdx
> +- - -
```suggestion
---
```

2022-09-16 14:54 UTC, BRKalow commented on website/content/docs/install/index.mdx
> +- - -
```suggestion
---
```

2022-09-16 15:09 UTC, tunzor requested changes
Couple snags from the script to fix (adding extra hash links and trying to escape characters) and a few link fixes.

2022-09-16 15:09 UTC, tunzor commented on website/content/intro/index.mdx
> +See the [Use Cases](/intro/use-cases) and [Who Uses Nomad](/docs/who-uses/noamd) page to understand the many ways Nomad is used in production today across many industries to solve critical, real-worl
The `Who Uses Nomad` page no longer exists in the newer versions.
```suggestion
See the [Use Cases](/intro/use-cases) page to understand the many ways Nomad is used in production today across many industries to solve critical, real-world business objectives.
```

2022-09-16 15:09 UTC, tunzor commented on website/data/intro-nav-data.json
> -      {
Think this should be:
```
{
    "title": "Clustering",
    "href": "https://learn.hashicorp.com/tutorials/nomad/clustering"
},
```

2022-09-16 15:16 UTC, BRKalow commented on website/content/docs/configuration/vault.mdx
> +  [tls_require_and_verify_client_cert](https://www.vaultproject.io/docs/configuration/listener/tcp#tls_require_and_verify_client_cert#tls_require_and_verify_client_cert)
Oops, good catch!

2022-09-16 15:33 UTC, tunzor approved these changes

2022-09-16 15:38 UTC, merged