Check that JobPlanResponse Diff Type is None before checking for changes on getExitCode
hashicorp/nomad pull request #14492
Opened 2022-09-08 11:04 UTC by gabivlj

Hi everyone! 

* This PR is strongly related to https://github.com/hashicorp/nomad/issues/2012, where if you:
`nomad plan ...`
and there are new allocations it should give an exit status code of 1.
* However if you do:
`nomad run ...`
and then:
`nomad plan ...`
It still returns an exit status code of 1.

These changes prevent that from happening, as if there wasn't any edits to the deployment file `resp.Diff.Type` is 'None', and it gives an exit status code of 0.
I'm wondering if this is the right solution for this problem or we are searching for a better one.

2022-09-08 11:04 UTC, hashicorp-cla commented
[![CLA assistant check](https://cla.hashicorp.com/pull/badge/not_signed)](https://cla.hashicorp.com/hashicorp/nomad?pullRequest=14492)


Thank you for your submission! We require that all contributors sign our Contributor License Agreement ("CLA") before we can accept the contribution. [Read and sign the agreement](https://cla.hashicorp.com/hashicorp/nomad?pullRequest=14492)

[Learn more about why HashiCorp requires a CLA and what the CLA includes](https://www.hashicorp.com/cla)


---
**Gabriel Villalonga Simon** seems not to be a GitHub user.
You need a GitHub account to be able to sign the CLA. If you already have a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).

<sub>Have you signed the CLA already but the status is still pending? [Recheck it](https://cla.hashicorp.com/check/hashicorp/nomad?pullRequest=14492).</sub>

2022-09-12 15:27 UTC, th0m commented
@tgross unless we have missed something (which we might have :grin:) this seems to be a straightforward way of fixing #2012

2022-09-21 16:39 UTC, th0m commented
@jrasell do you think you could have a look at this one? It should be relatively quick to review. Thank you

2022-10-03 20:23 UTC, tgross requested changes
LGTM, thanks @gabivlj!


<details><summary>test</summary>

```
$ nomad job plan ./jobs/periodic.nomad
+ Job: "example"
+ Task Group: "group" (1 create)
  + Task: "task" (forces create)

Scheduler dry-run:
- All tasks successfully allocated.
- If submitted now, next periodic launch would be at 2022-10-03T21:30:00-07:00 (8h11m20s from now).

Job Modify Index: 0
To submit the job with version verification run:

nomad job run -check-index 0 ./jobs/periodic.nomad

When running the job with the check-index flag, the job will only be run if the
job modify index given matches the server-side version. If the index has
changed, another user has modified the job and the plan's results are
potentially invalid.

$ echo $?
1

$ nomad job run ./jobs/periodic.nomad
Job registration successful

Approximate next launch time: 2022-10-03T21:30:00-07:00 (8h11m15s from now)

$ nomad job plan ./jobs/periodic.nomad
Job: "example"
Task Group: "group" (1 create)
  Task: "task"

Scheduler dry-run:
- All tasks successfully allocated.
- If submitted now, next periodic launch would be at 2022-10-03T21:30:00-07:00 (8h11m12s from now).

Job Modify Index: 11
To submit the job with version verification run:

nomad job run -check-index 11 ./jobs/periodic.nomad

When running the job with the check-index flag, the job will only be run if the
job modify index given matches the server-side version. If the index has
changed, another user has modified the job and the plan's results are
potentially invalid.

$ echo $?
0
```

</details>

This just missed the merge window for Nomad 1.4.0, but I'll make sure it gets merged once that goes out and it'll land in the first regular release of Nomad 1.4.x.

In the meantime, if you want you can add a changelog file to this PR. It'll be at `.changelog/14492.txt` and have the format you can see in [.changelog/14749.txt](https://github.com/hashicorp/nomad/blob/main/.changelog/14749.txt). For content, probably something like:

```
cli: Fixed a bug where plans for periodic jobs would return exit code 1 when the job was already register
```

(If you don't get to it before I'm ready to merge this, no worries. I see the PR has been open a little bit and it'll only take me a few minutes to add it.)

2022-10-03 20:26 UTC, tgross approved these changes

2022-10-06 20:23 UTC, merged

2022-10-06 20:23 UTC, tgross commented
Hi @gabivlj! We had to push out a quick Nomad 1.4.1 patch, but this has now been merged and will go out in the next regular patch release! Thanks again!