enhancement: UpdateTask when Task is waiting for ShutdownDelay
hashicorp/nomad pull request #14775
Opened 2022-10-02 17:29 UTC by DarthBenro008

Signed-off-by: Hemanth Krishna <hkpdev008@gmail.com>

- Fixes #14170 
- Adds a new Task Event named `TaskWaitingShuttingDownDelay ` (Open to suggestions)

2022-10-02 17:29 UTC, hashicorp-cla commented
[![CLA assistant check](https://cla.hashicorp.com/pull/badge/not_signed)](https://cla.hashicorp.com/hashicorp/nomad?pullRequest=14775)


Thank you for your submission! We require that all contributors sign our Contributor License Agreement ("CLA") before we can accept the contribution. [Read and sign the agreement](https://cla.hashicorp.com/hashicorp/nomad?pullRequest=14775)

[Learn more about why HashiCorp requires a CLA and what the CLA includes](https://www.hashicorp.com/cla)

<sub>Have you signed the CLA already but the status is still pending? [Recheck it](https://cla.hashicorp.com/check/hashicorp/nomad?pullRequest=14775).</sub>

2022-10-02 17:38 UTC, cesarvspr commented
this looks good @DarthBenro008 ! 

Would you please provide instructions on how can I test it?

2022-10-02 17:43 UTC, cesarvspr reviewed
see https://github.com/hashicorp/nomad/pull/14775#issuecomment-1264695659

2022-10-02 17:49 UTC, DarthBenro008 commented
@cesarvspr , you can create a [Task with shutdown delay](https://www.nomadproject.io/docs/job-specification/task#shutdown_delay) and then run `nomad alloc status` . It should show that the Task is waiting for the shutdown delay

2022-10-03 18:50 UTC, tgross requested changes
Hi @DarthBenro008, this is great!

I've left some suggestions this could be made even better. Also, can you add a changelog entry file? It'll be a file at `.changelog/14775.txt` that's in the format like [this one](https://github.com/hashicorp/nomad/blob/main/.changelog/14742.txt). For the text, it can be something like:

```
client: Added a TaskEvent when task shutdown is waiting on shutdown_delay
```

This just missed the window for Nomad 1.4.0 GA, but once this is merged you can expect this to ship in the next regular release of Nomad. Thanks so much!

2022-10-03 18:50 UTC, tgross commented on nomad/structs/structs.go
> +	TaskWaitingShuttingDownDelay = "Task waiting for shutdown delay"
If we look at the output of these, this name is a little wide and pushes everything to the right:

```
Recent Events:
Time                       Type                             Description
2022-10-03T14:25:34-04:00  Task waiting for shutdown delay  Waiting for shutdown delay before killing the task.
2022-10-03T14:25:34-04:00  Killing                          Sent interrupt. Waiting 5s before force killing
2022-10-03T14:25:15-04:00  Started                          Task started by client
2022-10-03T14:25:15-04:00  Task Setup                       Building Task Directory
2022-10-03T14:25:14-04:00  Received                         Task received by client
```

<img width="775" alt="Screen Shot 2022-10-03 at 2 38 26 PM" src="https://user-images.githubusercontent.com/1409219/193653527-8fe279db-f0ab-4da5-9259-932ee33debcc.png">

The event description can have more information about how we're waiting specifically on the `shutdown_delay` field and for how long, so for this event title, what if we trimmed it down to:

```suggestion
	TaskWaitingShuttingDownDelay = "Waiting for shutdown"
```

That also gives us some wiggle room to add new "waiting for shutdown" events with different sources/descriptions in the future.

2022-10-03 18:50 UTC, tgross commented on client/allocrunner/taskrunner/task_runner.go
> +			SetDisplayMessage("Waiting for shutdown delay before killing the task.")
For the display message we usually try to provide a little more information than is in the event type name. What if we told the user how long they'll be waiting:

```suggestion
			SetDisplayMessage(
				fmt.Sprintf("Waiting for shutdown_delay of %s before killing the task", delay))			
```

2022-10-04 06:32 UTC, DarthBenro008 commented
Hi @tgross, thanks a lot for the detailed review! 😃 . I have made the necessary amendments!

2022-10-06 20:33 UTC, tgross approved these changes
LGTM! Thanks @DarthBenro008! This should ship in the next regular patch release of Nomad

2022-10-06 20:33 UTC, merged