feat: Add nomad fmt
hashicorp/nomad pull request #14779
Opened 2022-10-03 13:10 UTC by Trojan295

This PR adds the `nomad fmt` command, which can be used to format and check Nomad configuration and jobspec files.

It formats the files according to the HCL syntax using [hashicorp/hcl](https://github.com/hashicorp/hcl/). It does not validate, if the files are correct Nomad or Jobspec files.

Closes https://github.com/hashicorp/nomad/issues/11757

2022-10-03 13:10 UTC, hashicorp-cla commented
[![CLA assistant check](https://cla.hashicorp.com/pull/badge/not_signed)](https://cla.hashicorp.com/hashicorp/nomad?pullRequest=14779)


Thank you for your submission! We require that all contributors sign our Contributor License Agreement ("CLA") before we can accept the contribution. [Read and sign the agreement](https://cla.hashicorp.com/hashicorp/nomad?pullRequest=14779)

[Learn more about why HashiCorp requires a CLA and what the CLA includes](https://www.hashicorp.com/cla)

<sub>Have you signed the CLA already but the status is still pending? [Recheck it](https://cla.hashicorp.com/check/hashicorp/nomad?pullRequest=14779).</sub>

2022-10-04 18:11 UTC, tgross requested changes
Hi @Trojan295! This is great!

I've left some comments that can tighten this up and make it more consistent with both `terraform fmt` and the rest of the Nomad code base. Two more things:

* You can add a changelog file. You'll make that at `.changelog/14779.txt` and it'll look like https://github.com/hashicorp/nomad/blob/main/.changelog/14742.txt. 
* There's documentation at [./website/content/docs/commands](https://github.com/hashicorp/nomad/tree/main/website/content/docs/commands). You can take a crack at mimicking the files in the top of that directory, but if that's too overwhelming just let me know and I can knock that out pretty quickly once this is ready to merge.

Thanks again!

2022-10-04 18:11 UTC, tgross commented on command/fmt.go
> +		Print the formatted files to stdout, instead of overwriting the file content.
Let's call this `write` to match `terraform fmt` (ref https://developer.hashicorp.com/terraform/cli/commands/fmt#write-false).

2022-10-04 18:11 UTC, tgross commented on command/fmt.go
> +	fmtArgs.Paths = flags.Args()
As my colleague @mikenomitch noted in https://github.com/hashicorp/nomad/issues/11757#issuecomment-1266090490, let's also allow this to accept `-` to read files from stdin.

2022-10-04 18:11 UTC, tgross commented on command/fmt.go
> +	with .nomad and .hcl extensions in the directory.
`terraform fmt` doesn't do this by default and has a separate [-recursive](https://developer.hashicorp.com/terraform/cli/commands/fmt#recursive) option. We should probably do the same.

2022-10-04 18:11 UTC, tgross commented on command/fmt_test.go
> +	f, err := os.CreateTemp("", "nomad-fmt-")
This leaves temp files on the test host when we're done. You can use [`t.TempDir`](https://pkg.go.dev/testing#T.TempDir) to get a directory that'll automatically get cleaned up afterwards.

2022-10-05 08:34 UTC, Trojan295 commented on command/fmt.go
> +		"-overwrite=false": complete.PredictNothing,
My idea behind this was, that by default the `overwrite` defaults to `true`, so someone would provide the flag to change this flag to `false`. That's why I think it's easier, if this autocompletes to `false` already.

2022-10-05 12:37 UTC, tgross commented on command/fmt.go
> +		"-overwrite=false": complete.PredictNothing,
Ah yeah, I misread the docstring here.

2022-10-05 16:03 UTC, tgross requested changes
Looking great @Trojan295! Just a few last items to fix up and we'll be able to land this one.

2022-10-05 16:03 UTC, tgross commented on website/content/docs/commands/fmt.mdx
> +---
I forgot that we need to add this page to the navbar for it to be rendered. If you add this bit of JSON:

```
      {
        "title": "fmt",
        "path": "commands/fmt"
      },
```

between the "commands/eval" and "commands/jobs" at https://github.com/hashicorp/nomad/blob/main/website/data/docs-nav-data.json#L431-L432, that'll allow our preview build for the docs to work.

2022-10-05 18:04 UTC, Trojan295 commented
Thanks @tgross for the review! I will update this PR tomorrow. :)

2022-10-06 08:42 UTC, Trojan295 commented on command/testdata/fmt/nomad.in.hcl
> +server {
What do you think about ignoring the `./command/testdata` directory from the `make hclfmt`?
```
   -o -path './command/testdata' -prune \
```

2022-10-06 20:38 UTC, tgross commented on command/testdata/fmt/nomad.in.hcl
> +server {
Eh, that'll work.

2022-10-06 20:40 UTC, tgross approved these changes
Looks great, @Trojan295! Thanks for sticking with it, I know PRs for new commands can feel like a whole lot of nitpicking 😀 

CircleCI seems to have gotten confused about the PR and can't run the build. So I just rebased this branch on `main` to get that moving again. Once that finishes, we can get this merged. ~(I'll probably have to do that tomorrow morning, as I'm close to end-of-day here.)~ _Done_

2022-10-06 21:00 UTC, merged

2022-10-06 21:06 UTC, tgross commented
@Trojan295 this has been merged and a backport bot will merge it to the 1.4.x release branch for the next patch release of Nomad . If that bot can't figure things out and requests a review from you, don't worry about it and I'll fix it in the morning; it's one of those fiddly process things we try not to expose to contributors but the bot is working thru a bit of a queue at the moment and I won't be there to immediately catch it. 😀

2022-10-06 21:35 UTC, Trojan295 commented
> Looks great, @Trojan295! Thanks for sticking with it, I know PRs for new commands can feel like a whole lot of nitpicking 😀

Wasn't so bad :). I just had a though, that it would be nice, if some of those docs/CLI help could be generated. E.g. we have the help in `mdx` and this gets automatically added to the website and also the CLI help is generated out of it.

2022-10-07 12:37 UTC, tgross commented
> I just had a though, that it would be nice, if some of those docs/CLI help could be generated.

Yes! I know a few folks have been tinkering around with better CLI generation internally for that reason.