Fix s3 example URLs in the artifacts docs
hashicorp/nomad pull request #15123
Opened 2022-11-03 15:17 UTC by twunderlich-grapl

Unfortunately, s3 urls prefixed with https:// do _NOT_ work with the underlying go-getter library. As such, this fixes the examples so that they are working examples that won't cause problems for people reading the docs. 

This is a known limitation of the go-getter lib since at least 2016 per https://github.com/hashicorp/nomad/issues/1113

I've also put up a PR with the underlying go-getter lib to fix their docs as well: https://github.com/hashicorp/go-getter/pull/394

2022-11-04 21:41 UTC, lgfa29 requested changes
Thanks for the fix @twunderlich-grapl!

Per your findings and existing documentation ("non-Amazon S3-compatible endpoints like Minio are supported, but you must explicitly set the "s3::" prefix.") using the explicit `s3://` protocol may be the example that is most likely to work in different scenarios.

How do you feel about setting it in the docs?

2022-11-04 21:41 UTC, lgfa29 commented on website/content/docs/job-specification/artifact.mdx
> +  source = "my-bucket-example.s3-us-west-2.amazonaws.com/my_app.tar.gz"
```suggestion
  source = "s3://my-bucket-example.s3-us-west-2.amazonaws.com/my_app.tar.gz"
```

2022-11-04 21:41 UTC, lgfa29 commented on website/content/docs/job-specification/artifact.mdx
> +  source = "my-bucket-example.s3-eu-west-1.amazonaws.com/my_app.tar.gz"
```suggestion
  source = "s3://my-bucket-example.s3-eu-west-1.amazonaws.com/my_app.tar.gz"
```

2022-11-07 15:06 UTC, twunderlich-grapl commented on website/content/docs/job-specification/artifact.mdx
> +  source = "my-bucket-example.s3-us-west-2.amazonaws.com/my_app.tar.gz"
I've updated this in a follow-up commit

2022-11-07 15:08 UTC, twunderlich-grapl commented
@lgfa29,
I've updated the example based on your suggestion. I agree that its the most likely way to avoid confusion since it will have an explicit protocol.

2022-11-07 19:14 UTC, lgfa29 approved these changes
Awesome, thanks!

2022-11-07 19:14 UTC, merged