bug:  enable `jobs.index` page to update in real-time
hashicorp/nomad pull request #15365
Opened 2022-11-22 21:20 UTC by ChaiWithJai

Resolves #10555

The `jobs.index` view is bound the model set on the `jobs.index` route. This model does not reactively update to changes in the `ember-data` store (instead it is subscribed to a set of `RecordIdenitfiers`... I believe).

That's why we're able to see job updates, but when a new job is added, our view does not update.

To fix the problem, we need to send a notification to the controller after the `query` and associated callback resolves meaning that our payload has successfully been added/updated to our `ember-date` store.

We also have one more challenge handling the wildcard (`*`) namespace which is a defacto `findAll` query. We have updated our `matchingRecord` algorithm to handle this case.

2022-11-22 21:28 UTC, ChaiWithJai commented on ui/app/adapters/watchable.js
> +            return get(record, mapping.attr) === query[mapping.queryParam];
@philrenaud This algorithm needs more work. I tried to make it minimal change by only adding one life, which works great if no filters are applied... however, if we apply the `namespace` filter, we're could run into issues.

2022-11-22 21:30 UTC, ChaiWithJai commented on ui/app/controllers/jobs/index.js
> +    if ((!this.model || !this.model.jobs) && jobs) return [];
`bug`: This should say if 

```
if (!jobs) return []
```

2022-11-22 21:30 UTC, ChaiWithJai commented on ui/app/services/watch-list.js
> +  @service store;
`nit`: remove unused dependency

2022-11-22 21:32 UTC, ChaiWithJai commented on ui/app/services/watch-list.js
> +  jobUpdateCount = 0;
@philrenaud I tried to make the minimal surface change here. We could try to make this more generic by converting this into a dictionary, however, I imagine we could gut the watcher system once its time for a redesign.

2022-11-30 19:42 UTC, philrenaud requested changes
I am still not sure this is working as intended. I am using a management token with 2 jobs running (shown in the return here) on the default namespace, and I see no jobs in my index. (on the main branch, I see both jobs) 
![image](https://user-images.githubusercontent.com/713991/204893075-64959e7f-4f9c-48e5-aa74-4f20369e812f.png)

2022-12-01 01:54 UTC, lgfa29 commented
For me it never shows the job, even after a refresh. Here's a replay:
https://app.replay.io/recording/jobs-nomad--8a2cadb9-0747-4eb6-b7e9-a07244a22fdd

2022-12-01 15:47 UTC, ChaiWithJai commented
> I am still not sure this is working as intended. I am using a management token with 2 jobs running (shown in the return here) on the default namespace, and I see no jobs in my index. (on the main branch, I see both jobs) ![image](https://user-images.githubusercontent.com/713991/204893075-64959e7f-4f9c-48e5-aa74-4f20369e812f.png)

Looks like a namespace issue. We have this wonky behavior where the namespace filter only appears when there are multiple namespaces configured. I didn't handle the case where a user isn't using namespaces. Good catch!

2024-06-28 20:32 UTC, philrenaud commented
Resolved in https://github.com/hashicorp/nomad/pull/20452

2024-06-28 20:32 UTC, closed without merging