doc: specifiy the default output is of json format for `nomad quota inspect` command
hashicorp/nomad pull request #15984
Opened 2023-01-31 16:46 UTC by dttung2905

Hi team,

This PR will add the `-json` flag under Inspect options for `nomad quota inspect` cli command.
The command is under enterprise offering so its abit challenging to test locally. If you know of a way to do so, please let me know too!
Also, if you want to create a separate issue to track the addition of `-json` flag for various commands, I can create it as well

2023-02-02 02:12 UTC, dttung2905 commented
@jrasell if you could help reviewing this PR and provide insight on the issues I highlighted above 🙏

2023-02-02 09:49 UTC, jrasell reviewed
Hi @dttung2905 and thanks for raising this PR. I took a closer look into the quota inspect command (I've not previously used it) and it looks like JSON output is the current default unless you specify and Go template to use via the `-t` flag. This change therefore means the command requires a flag, whereas ideally flags should be optional.

An approach could be to have the `-json` flag default to true, and any supplied `-t` overrides this and results in the template being used. I don't believe this is a better approach to keeping the command the way it is though, where JSON is the default output. Apologies I didn't see this before you raised the PR. Please let me know your thoughts on this.

2023-02-02 10:15 UTC, dttung2905 commented
> Hi @\dttung2905 and thanks for raising this PR. I took a closer look into the quota inspect command (I've not previously used it) and it looks like JSON output is the current default unless you specify and Go template to use via the `-t` flag. This change therefore means the command requires a flag, whereas ideally flags should be optional.
> 
> An approach could be to have the `-json` flag default to true, and any supplied `-t` overrides this and results in the template being used. I don't believe this is a better approach to keeping the command the way it is though, where JSON is the default output. Apologies I didn't see this before you raised the PR. Please let me know your thoughts on this.

Hi @jrasell , thanks for confirming this behavior. I had my suspicion when looking at the example result in the [official doc](https://developer.hashicorp.com/nomad/docs/commands/quota/inspect) where the format is already in JSON :laughing: 

Another way I could think of is below. However, since the output is deeply nested, formatting the output data in the second last line will be complicated :point_down:  ( I could not test this idea out because this is Enterprise feature though ) 

```
	if json || len(tmpl) > 0 {
		out, err := Format(json, tmpl, data)
		if err != nil {
			c.Ui.Error(err.Error())
			return 1
		}

		c.Ui.Output(out)
		return 0
	}

	c.Ui.Output(aNewFunctionToFormatData(data))
	return 0
```
I guess what we need now is just extra doc (under this [section](https://github.com/hashicorp/nomad/blob/main/website/content/docs/commands/quota/inspect.mdx#usage) for example) to clarify the default JSON output behavior? Wdyt?

2023-02-07 14:17 UTC, dttung2905 commented
Hi @jrasell, I have reverted all the changes and go with the extra documentation approach. Could you help to review it again ? :pray:

2023-02-07 14:55 UTC, jrasell requested changes
Hi @dttung2905 and thanks for making the changes here. I have suggested a tiny grammar change, then I will get this merged.

2023-02-07 14:55 UTC, jrasell commented on website/content/docs/commands/quota/inspect.mdx
> +quota. The default output is in JSON format
```suggestion
quota. The default output is in JSON format.
```

2023-02-07 14:57 UTC, jrasell approved these changes
LGTM, thanks @dttung2905!

2023-02-07 15:34 UTC, merged