Add `-json` and `-t` flag for  `nomad acl token create` command
hashicorp/nomad pull request #16055
Opened 2023-02-04 14:37 UTC by dttung2905

Hi team,

This PR aims to add `-json` and `-t` flag for `nomad acl token create` command. This is related to issue #15894 

Example output:
- With `-json` flag
```
❯ nomad acl token create -type="management" -global=true \
  -name="Cluster A Replication Token" \
  -token="abcxyz" -ttl=10m -json
{
    "AccessorID": "83a61305-15c2-c78a-1c59-75c44afa7a13",
    "CreateIndex": 927,
    "CreateTime": "2023-02-04T09:39:33.710007669Z",
    "ExpirationTTL": 600000000000,
    "ExpirationTime": "2023-02-04T09:49:33.710007669Z",
    "Global": true,
    "ModifyIndex": 927,
    "Name": "Cluster A Replication Token",
    "Policies": null,
    "Roles": null,
    "SecretID": "6d23da6a-677d-c7b9-02ac-f1c41ad5f5d0",
    "Type": "management"
}

```
- With `-t` flag
```
❯ nomad acl token create -type="management" -global=true \
  -name="Cluster A Replication Token" \
  -token="abcxyz" -ttl=10m -t='{{ .ExpirationTTL }}'

10m0s

```

2023-02-06 12:13 UTC, jrasell requested changes
Hi @dttung2905 and thanks for raising this; it's looking great. I've made a couple of very minor suggestions inline. I also wonder if it would be possible to update the tests added slightly, in particular when testing the JSON flag to check we have valid JSON returned in the output writer. Thanks again!

2023-02-06 12:13 UTC, jrasell commented on .changelog/16055.txt
> +cli: Add -json and -t flag to nomad acl token create command
nit: wrap the "code" specific items
```suggestion
cli: Add `-json` and `-t` flag to `nomad acl token create` command
```

2023-02-06 12:13 UTC, jrasell commented on command/acl_token_create.go
> +    Output the ACL token information in a JSON format.
```suggestion
    Output the ACL token information in JSON format.
```

2023-02-06 12:13 UTC, jrasell commented on website/content/docs/commands/acl/token/create.mdx
> +- `-json`:Output the ACL token information in a JSON format.
```suggestion
- `-json`:Output the ACL token information in JSON format.
```

2023-02-06 16:03 UTC, dttung2905 commented
Hi @jrasell. Thanks for the super quick review. I didn't check the semantic of JSON output i.e. all KV pairs because I think its abit uncessary. Hence, I have only added a check for a proper JSON formatted output. Please let me know what you think on this :pray:

2023-02-07 10:38 UTC, jrasell approved these changes
Thanks for the updates @dttung2905 and LGTM! The unmarshal testing trick is something I have used elsewhere, so it's nice to see others see this as an approach to take. Thanks!

2023-02-07 11:05 UTC, merged