Add a parameter to the template config render_templates_once
hashicorp/nomad pull request #16050
Opened 2023-02-03 16:02 UTC by jeffreybolle

This changes the re-render behaviour of nomad templates so that they do not get re-rendered when the values associated with consul keys used in the templates change.

2023-02-03 16:02 UTC, hashicorp-cla commented
[![CLA assistant check](https://cla.hashicorp.com/pull/badge/not_signed)](https://cla.hashicorp.com/hashicorp/nomad?pullRequest=16050)


Thank you for your submission! We require that all contributors sign our Contributor License Agreement ("CLA") before we can accept the contribution. [Read and sign the agreement](https://cla.hashicorp.com/hashicorp/nomad?pullRequest=16050)

[Learn more about why HashiCorp requires a CLA and what the CLA includes](https://www.hashicorp.com/cla)


---
**Jeffrey Bolle** seems not to be a GitHub user.
You need a GitHub account to be able to sign the CLA. If you already have a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).

<sub>Have you signed the CLA already but the status is still pending? [Recheck it](https://cla.hashicorp.com/check/hashicorp/nomad?pullRequest=16050).</sub>

2023-02-06 11:58 UTC, jrasell requested changes
Hi @jeffreybolle and thanks for raising this PR.

This approach being on a per client basis raises concern that in heterogeneous clusters, allocations which require templates to be re-rendered on change, could be placed on clients which have this disabled. In order to avoid this, operators would need to ensure jobs have custom constraints which feels like a poor UX and unexpected behaviour.

I think therefore to have this feature added, the control of this would need to be performed via a parameter within the template block of the job specification. It would be great to also include some testing in any followup work. Please let me know your thoughts or if you have any questions.

2023-02-21 09:40 UTC, jeffreybolle commented
> Hi @jeffreybolle and thanks for raising this PR.
> 
> This approach being on a per client basis raises concern that in heterogeneous clusters, allocations which require templates to be re-rendered on change, could be placed on clients which have this disabled. In order to avoid this, operators would need to ensure jobs have custom constraints which feels like a poor UX and unexpected behaviour.
> 
> I think therefore to have this feature added, the control of this would need to be performed via a parameter within the template block of the job specification. It would be great to also include some testing in any followup work. Please let me know your thoughts or if you have any questions.

Thanks for the feedback, your reasoning makes sense.  I will update the pull request when I get a chance.

2024-09-20 09:48 UTC, jrasell commented
Hi @jeffreybolle, I am going to close this PR. If you managed to get time to make the suggested changes, then please feel free to reopen or create a new PR.

2024-09-20 09:48 UTC, closed without merging