Skip tests running locally without root access
hashicorp/nomad pull request #16222
Opened 2023-02-18 19:14 UTC by farbodahm

[After a short discussion](https://github.com/hashicorp/nomad/pull/16137#pullrequestreview-1301517321) with @tgross, I learned that some of the tests will fail if we run them locally and without root access.

This PR will add a functionality to skip tests if the tests:
- Are **not** running in CI environment (they are running locally)
- and if they are **not** running with Root access

In the current behavior, They are failing by saying something like: `operation not permitted`. Also it will log that the test is skipped, so if user wants to run them, she/he has to run it with root access.

**Note:** I used `make test | grep -C 5 "operation not permitted"` to find which tests require Root access, But it may not contain all of the tests which require root access; But probably this doesn't contain all of the tests.

Please let me know if anything is needed; Thanks.

2023-02-21 13:38 UTC, tgross reviewed
Hi @farbodahm! The CI run [7312099268]https://github.com/hashicorp/nomad/actions/runs/4212805695/jobs/7312099268) is showing a test panic in `TestGenericNotifier` in `helper/broker/notify_test.go` that you'll want to look into.

2023-02-22 07:52 UTC, farbodahm commented
@tgross I double checked that the part which I changed didn't have any effect on the test which was failing. Also I ran the test with different parameters locally and it was fine; So I just re-run the CI (by force pushing) and everything is fine now.

2023-02-23 14:51 UTC, tgross commented
Hey @farbodahm I'm tied up in another mini-project I'm trying to ship by end of the week. I'll pick this back up next week. Just wanted to let you know that I haven't forgotten about this! :grinning:

2023-02-23 18:27 UTC, farbodahm commented
@tgross No worries man, Please take your time and thanks for mentioning!

2023-03-01 15:51 UTC, tgross requested changes
Hi @farbodahm! This looks pretty good once the changes I've posted are resolved.

2023-03-01 20:35 UTC, tgross approved these changes
LGTM!

I'll have to wait a day to merge this -- we're in a very brief merge freeze on `main` because 1.5.0 GA is coming out shortly. But once that's live I can get this in. Thanks again, @farbodahm!

2023-03-02 06:57 UTC, farbodahm commented
@tgross No worries, Thank you so much for the review Tim.

2023-03-02 18:38 UTC, merged