fix host port handling for ipv6, fixes #16550
hashicorp/nomad pull request #16723
Opened 2023-03-30 07:04 UTC by valodzka

2023-04-18 23:23 UTC, lgfa29 requested changes
Thanks for the PR @valodzka!

Do you think you would be able to add some tests? I think something like [`TestEnvironment_AsList`](https://github.com/hashicorp/nomad/blob/3f7143f50b64afeb1e461295bde3d4f8f1077b66/client/taskenv/env_test.go#L155-L250) but using IPv6 addresses would do the trick. 

Feel free to reach out if you need any help 🙂

2023-04-18 23:23 UTC, lgfa29 commented on command/agent/agent_endpoint_test.go
> +		addr := net.JoinHostPort("%s:%d", member.Addr, member.Port)
```suggestion
		addr := net.JoinHostPort(member.Addr, member.Port)
```

2023-04-20 12:17 UTC, valodzka commented
> Do you think you would be able to add some tests? 

@lgfa29  I'm not very familiar with go but here is my try :)

2023-04-21 02:52 UTC, lgfa29 approved these changes
Thanks for the additional tests @valodzka, you're practically a Go pro at this point 😄 

I pushed a couple of commits to add a changelog entry and also to fix a tiny problem in one of the test.

2023-04-21 02:53 UTC, merged