docker: add cgroupns task config
hashicorp/nomad pull request #17702
Opened 2023-06-23 15:37 UTC by lgfa29

Add support for Docker's [`--cgroupns`](https://docs.docker.com/engine/reference/commandline/run/) flag.

2023-06-23 15:39 UTC, shoenig requested changes
@lgfa29 where is this coming from?

2023-06-23 15:41 UTC, lgfa29 commented
> @lgfa29 where is this coming from?

I was just updating the PR body 😄 

I was helping a member of the community to get an app running and they required this flag to get things working. Does it break anything in Nomad?

2023-06-23 16:43 UTC, lgfa29 commented
> It'd be helpful to get more info about the context there, those words in that order don't quite clarify what's going on

In this particular case it was k0s (https://docs.k0sproject.io/v1.27.2+k0s.0/k0s-in-docker/#1-initiate-k0s), but I ran into this before with something else, just don't remember exactly what 😅

2023-06-23 16:44 UTC, closed without merging

2023-10-05 15:52 UTC, thornycrackers commented
One use case I could see being related to this is trying to run the datadog agent in a container on nomad using the docker driver. From [the docs](https://docs.datadoghq.com/containers/docker/?tab=standard):

```
docker run -d --cgroupns host \
    --pid host \
    --name dd-agent \
    -v /var/run/docker.sock:/var/run/docker.sock:ro \
    -v /proc/:/host/proc/:ro \
    -v /sys/fs/cgroup/:/host/sys/fs/cgroup:ro \
    -e DD_SITE=<DATADOG_SITE> \
    -e DD_API_KEY=<DATADOG_API_KEY> \
    gcr.io/datadoghq/agent:7
```

I think the only way to do the currently would be to use raw exec?