[f-gh-17449-lease] Add lease mechanism to SDK
hashicorp/nomad pull request #18268
Opened 2023-08-21 12:02 UTC by Juanadelacuesta

2023-08-22 13:02 UTC, jrasell requested changes
Thanks for this @Juanadelacuesta and looking good. There are a couple of things to look at and fix-up; the dependency note is meaning CI is failing.

2023-08-22 14:23 UTC, Juanadelacuesta commented on api/locks.go
> +	"github.com/hashicorp/nomad/helper/uuid"
Im wondering if we could some client info that could be unique to each one, but I can't come up with anything

2023-08-22 14:43 UTC, Juanadelacuesta commented on api/locks.go
> +)
I dont remember what they were for initially, so let's remove them.

2023-08-22 14:45 UTC, Juanadelacuesta commented on api/locks.go
> +			return fmt.Errorf("locks: unable to start protected function: %w", err)
not entirely, let's make it more generic.

2023-08-22 15:05 UTC, Juanadelacuesta commented on api/locks.go
> +func (l *Locks) Acquire(ctx context.Context, callerID string) (string, error) {
I know it is not used currently, but it is very hard to test the lease algorithm if there is no way to identify who is trying to acquire the lock, I've been thinking about it, how to remove it, but nothing comes to mind. Also, not the best practice to leave it there for the future, but if we want to identify who is holding the lock in the future, for fencing or to inform other instances who is the current leader, leaving it in the signature makes sense?

2023-08-22 16:09 UTC, Juanadelacuesta commented on api/locks_test.go
> +	go hac2.Start(testCtx, s.Run(hac2.ID, testCtx))
Done!

2023-08-22 17:29 UTC, Juanadelacuesta commented on api/locks.go
> +func (ll *LockLeaser) Start(ctx context.Context, protectedFunc func(ctx context.Context) error) error {
Sure, this protected function is the function that runs only when the instance holds the lock, so it is meant to be provided by the user.

2023-08-23 11:28 UTC, Juanadelacuesta commented on api/locks.go
> +	defer ll.locker.Release(ctx)
Done!

2023-09-06 14:30 UTC, jrasell reviewed
just a few questions, but looking greaaaat.

2023-09-06 15:22 UTC, Juanadelacuesta commented on api/locks.go
> +type Locker interface {
It is also implemented by the lock handler

2023-09-06 18:13 UTC, Juanadelacuesta commented on api/locks.go
> +	LockNoPathErr = errors.New("the path for the lock provided")
I was missing that validation, added it!

2023-09-07 12:40 UTC, jrasell approved these changes
https://www.reactiongifs.com/r/2011/05/amazing.gif

2023-09-07 16:54 UTC, merged