fix: use interpolated address when performing health checks
hashicorp/nomad pull request #18584
Opened 2023-09-26 10:03 UTC by MattJustMatt

Fixes #18574

2023-09-27 06:47 UTC, jrasell requested changes
Hi @MattJustMatt and thanks for the PR. The approach seems right to me, but. the change in function signature has broken some tests, which will need to be fixed up. It would also be nice to add some additional tests to cover the new behaviour and ensure interpolated service checks work as we now expected. Finally, a changelog entry for the addition can be included by running the `make cl` command.


Thanks again!

2023-09-28 06:43 UTC, MattJustMatt commented
@jrasell Thanks for the review! 

I've fixed the broken tests and added the changelog entry. I don't have a good enough understanding of the test infra to easily add a regression test for this, but if it's needed for this PR please let me know and I can dive in deeper.

2023-10-02 13:56 UTC, shoenig commented on .changelog/18584.txt
> +fix: use interpolated address when performing health checks
```suggestion
services: use interpolated address when performing nomad service health checks
```

2023-10-03 17:29 UTC, MattJustMatt commented
100% cool with me!

2023-10-04 12:51 UTC, shoenig approved these changes

2023-10-04 12:53 UTC, jrasell approved these changes

2023-10-04 12:58 UTC, merged