Clarify docs around CSI volume context updates
hashicorp/nomad pull request #19216
Opened 2023-11-29 14:47 UTC by sofixa

Clarify that when updating a CSI volume's `context` via `nomad volume register`, all parameters need to be specified, not only those to be updated.

2023-11-29 15:43 UTC, tgross requested changes

2023-11-29 15:43 UTC, tgross commented on website/content/docs/other-specifications/volume/index.mdx
> +  replaces it in its entirety, thefore all paramters need to be specified.
The wording here makes it sound a little bit like this is an exception. Maybe something like:

```suggestion
  **volume registration**. Note that, like the rest of the volume specification, 
  this block is declarative, and an update replaces it in its entirety, therefore 
  all parameters need to be specified.
```

(Also fixes spelling errors)

2023-11-29 15:44 UTC, gulducat reviewed
Thanks for the clarification!

just a couple little typos to fix then I'll :heavy_check_mark: :)

2023-11-29 15:44 UTC, gulducat commented on website/content/docs/other-specifications/volume/index.mdx
> +  replaces it in its entirety, thefore all paramters need to be specified.
```suggestion
  **volume registration**. Note that this block is declarative, and an update 
  replaces it in its entirety, therefore all parameters need to be specified.
```

2023-11-29 15:45 UTC, gulducat commented on website/content/docs/other-specifications/volume/index.mdx
> +  replaces it in its entirety, thefore all paramters need to be specified.
woops, simultaneous review from Tim and me :P

2023-11-30 18:21 UTC, tgross approved these changes
LGTM!

2023-12-01 07:47 UTC, jrasell approved these changes

2023-12-01 15:19 UTC, merged