Docs: Alternative IIS Task Driver
hashicorp/nomad pull request #19411
Opened 2023-12-10 11:08 UTC by sevensolutions

I'am working on an alternative IIS task driver for a while.
If you find this usefull for the entire community, feel free to merge this PR to list it on the community-plugins page.

Source Repo: https://github.com/sevensolutions/nomad-iis

2023-12-10 11:09 UTC, hashicorp-cla commented
[![CLA assistant check](https://cla.hashicorp.com/pull/badge/not_signed)](https://cla.hashicorp.com/hashicorp/nomad?pullRequest=19411)


Thank you for your submission! We require that all contributors sign our Contributor License Agreement ("CLA") before we can accept the contribution. [Read and sign the agreement](https://cla.hashicorp.com/hashicorp/nomad?pullRequest=19411)

[Learn more about why HashiCorp requires a CLA and what the CLA includes](https://www.hashicorp.com/cla)

<sub>Have you signed the CLA already but the status is still pending? [Recheck it](https://cla.hashicorp.com/check/hashicorp/nomad?pullRequest=19411).</sub>

2024-01-10 08:57 UTC, jrasell requested changes
Hi @sevensolutions and thanks for raising this PR. I have suggested some changes which remove the term alternative, as this driver shouldn't be classed as such as it indicates we have a preference. Once this changes has been pushed, I'll get this merged.

2024-01-10 08:57 UTC, jrasell commented on website/content/plugins/drivers/community/index.mdx
> +- [Windows IIS (Alternative)][nomad-iis]
```suggestion
- [Windows IIS][nomad-iis]
```

2024-01-10 08:57 UTC, jrasell commented on website/content/plugins/drivers/community/nomad-iis.mdx
> +# Windows IIS Driver (Alternative)
```suggestion
# Windows IIS Driver
```

2024-01-10 08:57 UTC, jrasell commented on website/data/docs-nav-data.json
> +            "title": "Windows IIS (Alternative)",
```suggestion
            "title": "Windows IIS",
```

2024-01-10 08:57 UTC, jrasell commented on website/data/plugins-nav-data.json
> +            "title": "Windows IIS (Alternative)",
```suggestion
            "title": "Windows IIS",
```

2024-01-10 08:57 UTC, jrasell commented on website/content/plugins/drivers/community/nomad-iis.mdx
> +This plugin is an alternative Task Driver to run IIS Web Applications on Windows Servers. Each allocation will create an AppPool and a Website.
```suggestion
This plugin is a task driver to run IIS Web Applications on Windows Servers. Each allocation will create an AppPool and a Website.  
```

2024-01-10 14:14 UTC, jrasell approved these changes
LGTM, thanks @sevensolutions!

2024-01-10 14:14 UTC, merged

2024-02-15 17:37 UTC, sevensolutions commented
@jrasell do you have an idea, why this changes arent on the stable-website branch anymore?
They have been backported by #19693 and i know they were there, but now they are not there anymore but the files are still in the main branch.

This was the link:
https://developer.hashicorp.com/nomad/plugins/drivers/community/nomad-iis

Maybe theres an issue with the backporting pipeline?