Updates and fixes out of data AWS packer and terraform code
hashicorp/nomad pull request #19512
Opened 2023-12-18 19:12 UTC by nickwales

The "Provision a Nomad cluster in the cloud" works in AWS with these updates to
- use an available ubuntu version
- uses hashicorp packages where possible

2024-01-31 17:53 UTC, nickwales commented on terraform/shared/config/consul.hcl
> +bind_addr = "0.0.0.0"
Agreed, this demo environment is lacking the security we'd expect in production. We could follow up with some improvements in that regard.

2024-01-31 17:53 UTC, nickwales commented on terraform/shared/scripts/setup.sh
> +NOMADVERSION=1.7.1
Done!

2024-01-31 17:55 UTC, nickwales commented on terraform/shared/scripts/client.sh
> +# Systemd-resolved config
Explained and added link to the documentation

2024-03-27 20:09 UTC, MikaelHashiCorp commented on terraform/shared/scripts/setup.sh
> +NOMADVERSION=1.7.1
I suggest to bump all versions to latest point release before merge.

2024-03-28 14:10 UTC, nickwales commented on terraform/shared/scripts/setup.sh
> +NOMADVERSION=1.7.1
Done

2024-04-16 13:04 UTC, tgross requested changes
@nickwales can you run `terraform fmt` on the Terraform files here? `make check` is failing:

```
==> Formatting HCL
make[1]: Leaving directory '/home/runner/work/nomad/nomad'
the following HCL files are out of sync
 M terraform/aws/modules/hashistack/hashistack.tf
 M terraform/shared/config/consul.hcl
 M terraform/shared/config/consul_client.hcl
```

Once that's done, this should be good to merge. I'd really love it if we could circle back and make this more production-ready with recommended configuration for security, but we can do that under a separate PR.

2024-04-16 14:46 UTC, tgross approved these changes

2024-04-16 14:47 UTC, merged