docs: autoscaler doc for max_scale_up and max_scale_down of target-value strategy
hashicorp/nomad pull request #19945
Opened 2024-02-12 11:15 UTC by brmzkw

See https://github.com/hashicorp/nomad-autoscaler/pull/848

2024-02-12 14:01 UTC, jrasell requested changes
Hi @brmzkw and thanks for raising this. It's looking good from my end, with a couple of minor changes requested.

2024-02-12 14:01 UTC, jrasell commented on website/content/tools/autoscaling/plugins/strategy/target-value.mdx
> +- `max_scale_up` `(int: unlimited)` - specifies the maximum number of instances
```suggestion
- `max_scale_up` `(int: unlimited)` - Specifies the maximum number of instances
```

2024-02-12 14:01 UTC, jrasell commented on website/content/tools/autoscaling/plugins/strategy/target-value.mdx
> +- `max_scale_down` `(int: unlimited)` - specifies the maximum number of instances
```suggestion
- `max_scale_down` `(int: unlimited)` - Specifies the maximum number of instances
```

2024-02-12 14:12 UTC, brmzkw commented
fixed :-)

2024-02-13 02:14 UTC, lgfa29 approved these changes
Thanks @brmzkw!

2024-02-13 07:38 UTC, jrasell approved these changes
LGTM, thanks @brmzkw!

2024-02-13 07:38 UTC, merged