Prevent NPE when service lacks identity
hashicorp/nomad pull request #19987
Opened 2024-02-14 20:06 UTC by sorenisanerd

Fixes a null pointer exception if `Alloc.SignIdentities` was called for any service and any service lacked an identity.

Fixes #19986

2024-02-14 20:06 UTC, hashicorp-cla commented
[![CLA assistant check](https://cla.hashicorp.com/pull/badge/not_signed)](https://cla.hashicorp.com/hashicorp/nomad?pullRequest=19987)


Thank you for your submission! We require that all contributors sign our Contributor License Agreement ("CLA") before we can accept the contribution. [Read and sign the agreement](https://cla.hashicorp.com/hashicorp/nomad?pullRequest=19987)

[Learn more about why HashiCorp requires a CLA and what the CLA includes](https://www.hashicorp.com/cla)

<sub>Have you signed the CLA already but the status is still pending? [Recheck it](https://cla.hashicorp.com/check/hashicorp/nomad?pullRequest=19987).</sub>

2024-02-14 20:13 UTC, tgross requested changes
Hi @sorenisanerd! Thanks for this PR. But I suspect the better place to fix this is in the `WIHandle` struct's `Equal` method in `nomad/structs/workload_id.go`. We typically try to gracefully handle it being nil in the method so that we're not having to nil check all over the code base (and, as in this case, apparently missing the nil check!)

Once you've made that change, if you can run `make cl` to add a changelog entry I'd be happy to get this merged in.

2024-02-14 22:00 UTC, tgross commented
@sorenisanerd can you do me a favor and sign the CLA as well here?

2024-02-14 22:33 UTC, sorenisanerd commented
I've poked our legal department about the CLA. Shouldn't take long.

2024-02-22 01:54 UTC, sorenisanerd commented
@tgross, I signed the CLA. I saw the CLA bot changed its comment to reflect that, but I don't know if you get the notified.

2024-02-22 14:00 UTC, tgross approved these changes
LGTM! Thanks @sorenisanerd!

2024-02-22 14:01 UTC, merged