#23671 Added synopsis for operator root and operator gossip command.
hashicorp/nomad pull request #23855
Opened 2024-08-22 13:37 UTC by raj-hegde

Synopsis comment for both gossip and root section has been added. Added the respective command files for each of the subcommands.

2024-08-22 13:41 UTC, raj-hegde commented
Please give feedback if I did anything wrong.

2024-09-18 09:34 UTC, jrasell requested changes
Hi @raj-hegde and thank you very much for raising this PR. I have added some minor suggestions for you to look at. Once these are resolved, I will get this PR merged.

2024-09-18 09:34 UTC, jrasell commented on command/operator_gossip.go
> +	`
When running the command locally, the output format seemed slightly off. The whitespace suggestion fixes that and the change to the usage keeps more consistency with other commands and correctly shows subcommand expectation. 

```suggestion
Usage: nomad operator gossip <subcommand> [options] [args]
	
  This command is accessed by using one of the subcommands below.
`
```

2024-09-18 09:34 UTC, jrasell commented on command/operator_gossip.go
> +func (f *OperatorGossipCommand) Run(args []string) int {
The args function parameter is unused, so we can use an underscore to show this is ignored.
```suggestion
func (f *OperatorGossipCommand) Run(_ []string) int {
```

2024-09-18 09:34 UTC, jrasell commented on command/operator_root.go
> +	`
When running the command locally, the output format seemed slightly off. The whitespace suggestion fixes that and the change to the usage keeps more consistency with other commands and correctly shows subcommand expectation.

```suggestion
Usage: nomad operator root <subcommand> [options] [args]

  This command is accessed by using one of the subcommands below.
`
```

2024-09-18 09:34 UTC, jrasell commented on command/operator_root.go
> +func (f *OperatorRootCommand) Run(args []string) int {
The args function parameter is unused, so we can use an underscore to show this is ignored.

```suggestion
func (f *OperatorRootCommand) Run(_ []string) int {
```

2024-09-18 09:34 UTC, jrasell commented on command/operator_root.go
> +func (f *OperatorRootCommand) Name() string { return "operator gossip" }
I think this may have been a copy/paste error :D

```suggestion
func (f *OperatorRootCommand) Name() string { return "operator root" }
```

2024-09-28 07:01 UTC, raj-hegde commented
Hi @jrasell, Thanks for the feedback I'll work on it right away.

2024-10-05 07:31 UTC, raj-hegde commented
Hi @jrasell  removed white spaces keeping consistency with other commands and changed the args function operator to underscore.  Also made a changlelog entry.

Any feedback is greatly appreciated.

2024-10-18 07:48 UTC, merged

2024-10-23 14:18 UTC, raj-hegde commented
@jrasell, Thank you