Add info about authentication
hashicorp/nomad pull request #23934
Opened 2024-09-08 10:27 UTC by johncooler

2024-09-18 13:00 UTC, jrasell requested changes
Hi @johncooler and thanks for raising this PR. I have made a suggestion to change the wording and formatting a little which I believe makes readability easier. Please let me know your thoughts. Once resolved, I'll get this merged.

2024-09-25 15:32 UTC, johncooler commented
of course, LGTM
approve

2024-10-03 14:13 UTC, aimeeu approved these changes
LGTM from a docs standpoint. Thanks for updating the podman content!

2024-10-29 15:45 UTC, jrasell approved these changes

2024-10-29 15:45 UTC, merged