scheduler: take all assigned cpu cores into account instead of only those part of the largest lifecycle
hashicorp/nomad pull request #24304
Opened 2024-10-27 14:17 UTC by mvegter

2024-11-08 15:57 UTC, mvegter commented
Hey @tgross @jrasell , if you have some time available in the next few business days I would appreciate a review on this PR, curious to your feedback !

2024-11-08 20:28 UTC, tgross commented
@mvegter just a heads up that we see this but it's going to take into next week to review... scheduler changes are particularly nasty and easy to get wrong, so its extra careful going.

2024-11-21 15:32 UTC, tgross requested changes
The changes you've made look great @mvegter! I've checked this branch out and applied it onto a Nomad Enterprise build as well to run through a relevant subset of tests on quotas and the plan applier with the various Enterprise features, and that looked good.

I've left one small comment about test coverage, but once that's resolved this should be good to merge. Thanks for your perseverance on getting this done!

2024-11-21 15:32 UTC, tgross commented on nomad/structs/structs_test.go
> +			},
For stronger test coverage, it'd be nice if we had a prestart sidecar task in here too.

2024-11-21 15:52 UTC, mvegter commented
> I've left one small comment about test coverage, but once that's resolved this should be good to merge. Thanks for your perseverance on getting this done!

Thanks @tgross , it was a nice journey through the Nomad scheduler and reading up on Linux Cpusets 😁

2024-11-21 18:21 UTC, tgross approved these changes
LGTM!

2024-11-21 18:21 UTC, merged

2024-11-21 18:33 UTC, tgross commented
Thanks again for this contribution @mvegter. This will get released in the next version of Nomad, along with backports to Nomad Enterprise 1.8.x+ent and 1.7.x+ent