fix: case where image got port number and not tag
hashicorp/nomad pull request #24547
Opened 2024-11-23 17:07 UTC by vincentDcmps

### Description

when using private registry without any image tag pull get *Invalid reference format* issue

### Testing & Reproduction steps

on version 1.9.4 send a job with image with following format:

```
ghcr.service.consul:5000/paperless-ngx/paperless-ng
```

### Reviewer Checklist
- [ ] **Backport Labels** Please add the correct backport labels as described by the internal
  backporting document.
- [ ] **Commit Type** Ensure the correct merge method is selected which should be "squash and merge"
  in the majority of situations. The main exceptions are long-lived feature branches or merges where
  history should be preserved.
- [ ] **Enterprise PRs** If this is an enterprise only PR, please add any required changelog entry
  within the public repository.

2024-12-03 19:33 UTC, vincentDcmps commented
Hi does something is missing in this PR to be review?

2025-01-02 17:25 UTC, vincentDcmps commented
could I have a feeback on this PR? I supose i'm not alone to use private registry?

2025-01-03 07:50 UTC, pkazmierczak requested changes
Hi @vincentDcmps, thanks a lot for the PR and apologies it took a while for anyone to take a look at it. Code looks good to me, I only left a formatting suggestion. Would you also mind adding a small changelog entry? You can make it with `make cl`, something like:
```
docker: Fix a bug where images with port number and no tags weren't parsed correctly.
```

Then I'm happy to merge.

2025-01-03 07:50 UTC, pkazmierczak commented on drivers/docker/driver_test.go
> +    {"host:5000/library/hello-world:1.0", "host:5000/library/hello-world", "1.0"},
```suggestion
		{"host:5000/library/hello-world", "host:5000/library/hello-world", "latest"},
		{"host:5000/library/hello-world:1.0", "host:5000/library/hello-world", "1.0"},
```

2025-01-03 08:26 UTC, pkazmierczak approved these changes
LGTM! Thanks, @vincentDcmps!

2025-01-03 10:38 UTC, merged