add noswap to secretdir tmpfs
hashicorp/nomad pull request #24645
Opened 2024-12-10 21:56 UTC by chuckyz

### Description
This adds `noswap` mount option to the `SecretDir` mount.

### Testing & Reproduction steps
- Create an allocation that triggers a secret dir creation

(having a hell of a time trying to get tests to run locally so I'm going to rely on GHA to run unit tests (fingers crossed))

### Links
todo issue

### Contributor Checklist
- [ ] **Changelog Entry** If this PR changes user-facing behavior, please generate and add a
  changelog entry using the `make cl` command.
- [x] **Documentation** If the change impacts user-facing functionality such as the CLI, API, UI,
  and job configuration, please update the  Nomad website documentation to reflect this. Refer to
  the [website README](../website/README.md) for docs guidelines. Please also consider whether the
  change requires notes within the [upgrade guide](../website/content/docs/upgrade/upgrade-specific.mdx).

### Reviewer Checklist
- [ ] **Backport Labels** Please add the correct backport labels as described by the internal
  backporting document.
- [ ] **Commit Type** Ensure the correct merge method is selected which should be "squash and merge"
  in the majority of situations. The main exceptions are long-lived feature branches or merges where
  history should be preserved.

2024-12-11 13:44 UTC, tgross requested changes
Hi @chuckyz, nice to hear from you!

This is a great idea, but the `noswap` option was only introduced in Linux 6.4 and so we can't apply it blindly (many users have older kernels). For example, on Ubuntu 22.04:

```
$ uname -r
5.15.0-126-generic
$ mkdir /home/tim/secrets
$ sudo mount -t tmpfs -o size=100M,noswap tmpfs /home/tim/secrets
mount: /home/tim/secrets: wrong fs type, bad option, bad superblock on tmpfs, missing codepage or helper program, or other error.

$ sudo mount -t tmpfs -o size=100M tmpfs /home/tim/secrets
$ mount | grep secrets
tmpfs on /home/tim/secrets type tmpfs (rw,relatime,size=102400k,inode64)
```

But I'd love to find a way to get this in because it's a good incremental improvement to security. We just need a way to test for this option at runtime (maybe try with swap and then fallback to not using it?).

Also, once we've got that figured out can you run `make cl` to add a changelog item? Thanks!

2024-12-11 17:14 UTC, chuckyz commented
Hey @tgross that sounds great.

Another option would potentially be `ramfs`, however then we'd (for safety/reliability) probably need to setup the bind-mount as read only and it'd probably make the code base a bit tougher as ideally there'd be an option for tmpfs, or ramfs.

I personally strongly prefer the idea of just sticking with tmpfs.

I was going to call `syscall.Uname`, and parse out >= 6.4, sound good?

2024-12-11 18:33 UTC, tgross commented
> I was going to call `syscall.Uname`, and parse out >= 6.4, sound good?

If we do that, we won't be applying it on RHEL9, where the kernel version is 5.14 but they've apparently backported the `noswap` option (in a [security patch](https://access.redhat.com/errata/RHSA-2024:4349.html), if you can believe that! This is what I was obliquely referring to as "frankenkernel"). So that's why I was suggesting we try with the `noswap` option and catch the error and retry if that fails.

2024-12-15 00:40 UTC, chuckyz commented
Gave this a shot, got tests _mostly_ working locally.  Would you consider maybe trying `syscall.MNT_DETACH` or sprinkling around `time.Sleep()` to make tests more consistent locally?  Not sure why but I'm really having a hard time actually un-mounting during cleanup phases of tests.

Also I got fancy with this solution and then realized KISS and tried to make this way simpler (catch error once, then try again before returning a real error).

2024-12-18 15:00 UTC, tgross requested changes
Looks great @chuckyz! One last item: can you run `make cl` to add a changelog entry. Something like "client: add noswap directive to secrets directory where supported on Linux"

2024-12-21 00:49 UTC, chuckyz commented
Should be good to go!

2025-01-06 14:44 UTC, tgross approved these changes
LGTM! Thanks @chuckyz!

2025-01-06 14:44 UTC, merged