keyring: warn if removing a key that was used for encrypting variables
hashicorp/nomad pull request #24766
Opened 2024-12-31 15:45 UTC by pkazmierczak

This PR adds an additional check in the `Keyring.Delete` RPC to make sure we're not trying to delete a key that's been used to encrypt a variable. It also adds a `-force` flag for the CLI/API to sidestep that check. 

Resolves https://github.com/hashicorp/nomad/issues/24591
Internal ref: https://hashicorp.atlassian.net/browse/NET-11829

2025-01-03 08:34 UTC, jrasell requested changes
Thanks for doing this @pkazmierczak!

I tested this locally and couldn't get a delete to work even when using the force flag. I believe we need to populate the RPC request force parameter from the HTTP request [here](https://github.com/hashicorp/nomad/blob/2f4353412d1bcf305898f676a815d342304ffa28/command/agent/keyring_endpoint.go#L190) in order for the HTTP->RPC translation to handle this new parameter.

It would also be good if we could address the following items:
- The CLI help output doesn't include the new flag option.
- It would be nice to have API and CLI tests to cover this addition as the RPC test did not catch the issue detailed above.
- Document the API and CLI changes.

2025-01-03 08:34 UTC, jrasell commented on .changelog/24766.txt
> +keyring: Warn if deleting a key previously used to encrypt a variable
Is it worth expanding on this to note the variable should still exist? It immediately reads to me that the warning applies to any key used in the past.

2025-01-03 08:34 UTC, jrasell commented on api/keyring.go
> +	Force bool
I know not many options have this, but could we add a comment to this explaining what the force boolean does? It means external tool developers have an easy time knowing and understanding.

2025-01-03 08:34 UTC, jrasell commented on nomad/keyring_endpoint.go
> +		return fmt.Errorf("root key in use, cannot delete")
There is no formatting, so we could use the below (the suggestion won't compile as the file also needs the new import):
```suggestion
		return errors.New("root key in use, cannot delete")
```

2025-01-03 10:41 UTC, pkazmierczak commented on nomad/keyring_endpoint.go
> +		return fmt.Errorf("root key in use, cannot delete")
yeah force of habit I guess, but `errors.New` is a better choice here

2025-01-03 15:41 UTC, aimeeu approved these changes
Thanks for updating the docs!

2025-01-03 15:50 UTC, pkazmierczak commented
@jrasell I addressed all your comments, thanks for the thorough review.

2025-01-07 08:24 UTC, jrasell approved these changes
LGTM, thanks @pkazmierczak!

I tested this locally on macOS attempting to delete root keys used for both variable encryption and task workload identity.

2025-01-07 09:15 UTC, merged