Display class in client details
hashicorp/nomad pull request #9166
Opened 2020-10-23 20:58 UTC by fqborges

Display node class in client detail at /ui/clients/{client-id}

also fixes https://github.com/hashicorp/nomad/issues/8547

2020-10-23 20:59 UTC, hashicorp-cla commented
[![CLA assistant check](https://cla.hashicorp.com/pull/badge/not_signed)](https://cla.hashicorp.com/hashicorp/nomad?pullRequest=9166)


Thank you for your submission! We require that all contributors sign our Contributor License Agreement ("CLA") before we can accept the contribution. [Read and sign the agreement](https://cla.hashicorp.com/hashicorp/nomad?pullRequest=9166)

[Learn more about why HashiCorp requires a CLA and what the CLA includes](https://www.hashicorp.com/cla)

<sub>Have you signed the CLA already but the status is still pending? [Recheck it](https://cla.hashicorp.com/check/hashicorp/nomad?pullRequest=9166).</sub>

2020-10-23 23:18 UTC, DingoEatingFuzz requested changes
Thank you for this!

I left a suggestion that will make tests pass (although bonus points if you add coverage for this change in [`/ui/tests/acceptance/client-detail-test.js`](https://github.com/hashicorp/nomad/blob/master/ui/tests/acceptance/client-detail-test.js)).

In addition to that suggestion, can you wrap this new pair in a `{{#if this.model.nodeClass}}{{/if}}`? Since node classes are optional, we don't want to show a blank value.

2020-10-23 23:18 UTC, DingoEatingFuzz commented on ui/app/templates/clients/client/index.hbs
> +      <span class="pair" data-test-datacenter-definition>
These data attributes used for tests need to be unique.

```suggestion
      <span class="pair" data-test-node-class>
```

2020-10-26 17:52 UTC, DingoEatingFuzz approved these changes
Perfect! Thank you for this. 

The test failures are unrelated since the UI tests passed ✅

2020-10-26 17:54 UTC, merged

2020-10-26 17:56 UTC, fqborges commented
Thanks. I am having trouble setting up vagrant in my windows box. I will try to add the test coverage later.