Event Stream: Track ACL changes, unsubscribe on invalidating changes
hashicorp/nomad pull request #9447
Opened 2020-11-25 16:48 UTC by drewbailey

When the event broker receives an ACL event type, re-run acl privilege checks for existing streams

2020-11-30 21:36 UTC, krishicks approved these changes
My approval here is implied because I paired with @drewbailey on a fair bit of it.

2020-12-01 13:37 UTC, tgross requested changes
LGTM except for what I think is a missing mutex.

2020-12-01 13:59 UTC, drewbailey commented on nomad/stream/event_broker.go
> +	e.mu.Lock()
Added a comment, `checkSubscriptionsAgainstPolicyChange` needs to lock for the broker to iterate over its subscriptions by token. The `structs.ACLTokenEvent` case is dealing only with a single token, so the broker doesn't need to iterate over all the subscriptions.

2020-12-01 15:15 UTC, tgross approved these changes

2020-12-01 15:16 UTC, tgross commented on nomad/stream/event_broker.go
> +	e.mu.Lock()
Gotcha. Thanks!

2020-12-01 16:11 UTC, merged