Document potential lifecycle values
hashicorp/nomad pull request #9659
Opened 2020-12-17 13:51 UTC by jrnk

I found these were missing in the docs after the mention of PostStop in the 1.0 release; I've used the same markdown style for the listing of values as f.e. present on https://www.nomadproject.io/docs/job-specification/update#health_check

2020-12-17 13:51 UTC, hashicorp-cla commented
[![CLA assistant check](https://cla.hashicorp.com/pull/badge/not_signed)](https://cla.hashicorp.com/hashicorp/nomad?pullRequest=9659)


Thank you for your submission! We require that all contributors sign our Contributor License Agreement ("CLA") before we can accept the contribution. [Read and sign the agreement](https://cla.hashicorp.com/hashicorp/nomad?pullRequest=9659)

[Learn more about why HashiCorp requires a CLA and what the CLA includes](https://www.hashicorp.com/cla)

<sub>Have you signed the CLA already but the status is still pending? [Recheck it](https://cla.hashicorp.com/check/hashicorp/nomad?pullRequest=9659).</sub>

2020-12-18 20:20 UTC, DingoEatingFuzz requested changes
Thank you for this! I had a small formatting suggestion, but the content is a welcome addition.

2020-12-18 20:20 UTC, DingoEatingFuzz commented on website/pages/docs/job-specification/lifecycle.mdx
> +  - "poststop" - Runs after all other tasks have finished.
A small suggestion to make this more consistent with other docs.

```suggestion
  - `prestart` - Runs prior to starting the main task.

  - `poststart` - Runs after starting the main task.

  - `poststop` - Runs after all other tasks have finished.
```

2020-12-18 20:22 UTC, DingoEatingFuzz approved these changes
On second thought, you're totally right that there are other docs that use strings instead of code formatting. I can't hold that against you 😅

2020-12-18 22:44 UTC, cgbaker commented
Hi @jrnk , I unfortunately just noticed this. Coincidentally, I happened to pick up an item today and merged PR #9693 with documentation of these fields, so I'm going to close this PR.

I appreciate your work here, and welcome other PRs in the future! Thanks, again!

2020-12-18 22:44 UTC, closed without merging