WTDD: Update UI api docs
hashicorp/nomad pull request #9690
Opened 2020-12-18 19:35 UTC by DingoEatingFuzz

These were very out of date, lol.

2020-12-18 21:10 UTC, backspace requested changes
whew, so much new material! I wonder if we can embed this in the code somehow in the future 🤔

I made a couple of spelling fix suggestions and maybe `page` has the wrong default but otherwise 👍😀

2020-12-18 22:01 UTC, DingoEatingFuzz commented on website/pages/api-docs/ui.mdx
> +- `page` `(int: 0)` - Specifies the page in the allocations list that should be visible. This
Good catch on this; I can update it throughout.

2021-01-07 13:57 UTC, backspace approved these changes
total success 🥳

2021-01-07 13:58 UTC, backspace commented
or not, I see there’s a merge conflict now 😞

2021-01-07 17:55 UTC, DingoEatingFuzz commented
I expected the merge conflicts. The `next-mdx-remote` migration merged yesterday. I'll get on the rebase.

2021-01-07 18:52 UTC, merged