UI: Add button to fail running deployments
hashicorp/nomad pull request #9831
Opened 2021-01-15 16:47 UTC by backspace

As suggested in #9826. The placement is currently ridiculous:

<img width="1188" alt="image" src="https://user-images.githubusercontent.com/43280/104754631-12721080-571f-11eb-9377-7709fe99f2cd.png">

2021-01-21 01:04 UTC, DingoEatingFuzz requested changes
This is a welcome addition. I have a couple thoughts, dunno how blocking they are, but I think they're at least worth talking through.

1. The `padding-bottom` specific value seems brittle. Ideally we can achieve the baseline matching in a way that still works if we change the button styles or button size.
2. Changing to the classes hash (which is a neat implementation, btw) really opens up the surface area of the component's API. I'm not saying it's wrong, but it gave me pause.

2021-02-09 21:33 UTC, backspace commented on ui/app/styles/components/two-step-button.scss
> +      padding-bottom: 6.462px;
yeah, that was admittedly ridiculous 😳 I couldn’t get those to work but what do you think about this?

```
  &.has-inline-text {
    display: inline-flex;
    align-items: center;

    button {
      margin-left: 0.3rem;
    }

    .confirmation-text {
      position: static;
      margin-right: 0.2rem;
    }
  }
```

I’ve learned while looking at this that the spaces between the button are true spaces, not CSS spaces, but with flexbox I added the `0.3rem` margins to bring back the space 🧐

2021-02-09 21:47 UTC, backspace commented
agreed that `@classes` is a significant expansion of the interface; my approach was driven by the way `isInfoAction` was handled:

<img width="1206" alt="image" src="https://user-images.githubusercontent.com/43280/107432471-a2706380-6aed-11eb-9b9f-d71dc5c51a7b.png">

I was reluctant to add another set of conditionals in each of those classes, but they could be extracted to computed properties instead. It seemed nice to me to be able to use `TwoStepButton` and style its components independently without having to change anything inside the component itself.

2021-02-10 00:13 UTC, DingoEatingFuzz commented on ui/app/styles/components/two-step-button.scss
> +      padding-bottom: 6.462px;
I dig it! There is also the hip new `ch` unit that is based on character width that may be worth experimenting with. With a variable width font I don't think this is as simple as `1ch`, you'd probably still need some fraction. And at that point maybe it doesn't even matter... I dunno.

2021-02-10 00:25 UTC, DingoEatingFuzz approved these changes
Reading through the `@classes` approach, I'm more comfortable with it this time. I think your summary of it being styling the individual pieces without having to fuss with structure sold me on it.

My root concern was opening up the API to the point where we aren't really providing a constraint in the way a style guide/design system should. But since the structure and components are fixed and only the individual modifiers are consumer-editable I think this is good 👍

2021-02-10 14:30 UTC, backspace commented
Thanks for the rereview! 💞

I `ch`anged to `ch` 😆

I encountered [this test failure](https://app.circleci.com/pipelines/github/hashicorp/nomad/14726/workflows/f4ae0bf2-0699-4d18-b55e-5221aafe393c/jobs/137128) but it’s surely unrelated and it disappeared when I reran, so I’ll look at it separately.

2021-02-10 14:38 UTC, merged