enabled hairpin mode
hashicorp/nomad pull request #9975
Opened 2021-02-04 20:21 UTC by AndrewChubatiuk

Fixes #9683

2021-02-09 14:35 UTC, AndrewChubatiuk commented
@nickethier @shoenig 
Could you guys please review this PR?

2021-02-09 15:01 UTC, grynko commented
Hi guys!

This MR seems to fix the issue we have with CNI. Could you please take a look?

Thanks @AndrewChubatiuk for your time!

2021-02-12 18:20 UTC, shoenig requested changes
This looks great @AndrewChubatiuk, thanks for digging in and getting this fixed!

Just the 2 minor nitpicks and I think this looks good. Also would be a good idea to rebase with master and make sure everything is still as it should be.

2021-02-12 18:20 UTC, shoenig commented on command/agent/consul/connect.go
> +				TCP:      ipaddr.FormatAddressPort(cMapping.HostIP, cMapping.Value),
Let's remove the extra non-`api/` consul dependency and just copy the implementation of `FormatAddressPort`, which is one line
```
func FormatAddressPort(address string, port int) string {                                                                                           
        return net.JoinHostPort(address, strconv.Itoa(port))                                                                                        
} 
```

2021-02-12 18:20 UTC, shoenig commented on command/agent/consul/connect.go
> +		return structs.AllocatedPortMapping{}, fmt.Errorf("invalid port %q: port label not found", portLabel)
To match with similar errors
```suggestion
		return structs.AllocatedPortMapping{}, fmt.Errorf(""No port of label %q defined", portLabel)
```

2021-02-12 18:21 UTC, shoenig commented
@AndrewChubatiuk if you don't have the time, I can follow up on Monday to make sure this gets into v1.0.4

2021-02-12 18:44 UTC, AndrewChubatiuk commented
@shoenig 
Thank you. If I will not manage to fix it till Monday, feel free to make requested updates on your own

2021-02-16 15:50 UTC, shoenig approved these changes
LGTM, thanks @AndrewChubatiuk !

2021-02-16 15:50 UTC, merged